#!/bin/sh

set -o errexit
set -o nounset

# Auto-restart worker on changes to Python code using watchdog
# see https://www.distributedpython.com/2019/04/23/celery-reload/
watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A transit_odp.taskapp worker -l INFO
