#!/bin/sh

set -o errexit
set -o nounset

# Auto-restart worker on changes to Python code using hupper
# see https://www.distributedpython.com/2019/04/23/celery-reload/
hupper -m celery -A transit_odp.taskapp worker --pool solo -l INFO
