# Generated by Django 4.1.13 on 2024-05-17 14:08

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("transmodel", "0026_alter_vehiclejourney_block_number"),
        ("organisation", "0059_alter_dataset_dataset_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation", models.CharField(max_length=1024)),
                ("importance", models.CharField(max_length=64)),
                ("category", models.CharField(max_length=64)),
                ("queue_name", models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(max_length=64, null=True)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dqs_report",
                        to="organisation.datasetrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskResults",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=64)),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Contains more details about the error"
                    ),
                ),
                (
                    "checks",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dqs_taskresults_check",
                        to="dqs.checks",
                    ),
                ),
                (
                    "dataquality_report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dqs_taskresults_report",
                        to="dqs.report",
                    ),
                ),
                (
                    "transmodel_txcfileattributes",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dqs_taskresults_txcfileattributes",
                        to="organisation.txcfileattributes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservationResults",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Contains more details about the error"
                    ),
                ),
                (
                    "service_pattern_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dqs_observationresult_service_pattern_stop",
                        to="transmodel.servicepatternstop",
                    ),
                ),
                (
                    "taskresults",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dqs_observationresult_taskresults",
                        to="dqs.taskresults",
                    ),
                ),
                (
                    "vehicle_journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dqs_observationresult_vehicle_journey",
                        to="transmodel.vehiclejourney",
                    ),
                ),
            ],
        ),
    ]
