# Generated by Django 4.1.13 on 2024-05-17 14:10

from django.db import migrations
from transit_odp.dqs.constants import CHECKS_DATA

def insert_updated_data(apps, schema_editor):
    Checks = apps.get_model("dqs", "Checks")
    for entry in CHECKS_DATA:
        Checks.objects.create(**entry)


class Migration(migrations.Migration):
    dependencies = [
        ("dqs", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_updated_data),
    ]
