# Generated by Django 4.2.14 on 2024-08-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dqs", "0003_alter_observationresults_service_pattern_stop_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"get_latest_by": "created"},
        ),
    ]
