# Generated by Django 4.2.9 on 2024-08-19 10:51

from django.db import migrations
from transit_odp.dqs.constants import Checks, Level, Category
from django.conf import settings

AWS_ENVIRONMENT = settings.AWS_ENVIRONMENT.lower()


class Migration(migrations.Migration):

    dependencies = [
        ("dqs", "0004_alter_report_options"),
    ]
    queue_name = f"dqs-{AWS_ENVIRONMENT}-no-timing-point-more-than-15-mins"

    operations = [
        migrations.RunSQL(
            "INSERT INTO dqs_checks(observation, importance, category, queue_name) VALUES ('"
            + Checks.CancelledServiceAppearingActive.value
            + "', '"
            + Level.advisory.value
            + "', '"
            + Category.timing.value
            + "', '"
            + queue_name
            + "')"
        )
    ]
