# Generated by Django 4.2.14 on 2024-09-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dqs", "0005_create_dqs_checks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"get_latest_by": "created"},
        ),
        migrations.AddField(
            model_name="observationresults",
            name="is_suppressed",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Contains whether the observation result is suppressed",
                null=True,
            ),
        ),
    ]
