# Generated by Django 4.2.14 on 2024-08-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dqs", "0006_create_dqs_check_missing_journey_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"get_latest_by": "created"},
        ),
    ]
