# Generated by Django 4.2.14 on 2024-10-22 12:36

from django.db import migrations, models
from transit_odp.dqs.constants import Checks, Level, Category
import django.db.models.deletion
from django.conf import settings

AWS_ENVIRONMENT = settings.AWS_ENVIRONMENT.lower()


class Migration(migrations.Migration):

    dependencies = [
        ("dqs", "0008_add_is_suppressed_observation_results"),
    ]
    queue_name = f"dqs-{AWS_ENVIRONMENT}-serviced-organisation-out-of-date"

    operations = [
        migrations.AddField(
            model_name="observationresults",
            name="serviced_organisation_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Contains the link to serviced organisation id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transmodel.servicedorganisations",
            ),
        ),
        migrations.RunSQL(
            "INSERT INTO dqs_checks(observation, importance, category, queue_name) VALUES ('"
            + Checks.ServicedOrganisationOutOfDate.value
            + "', '"
            + Level.advisory.value
            + "', '"
            + Category.data_set.value
            + "', '"
            + queue_name
            + "')"
        ),
    ]
