# Generated by Django 4.2.14 on 2024-10-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dqs", "0010_remove_observationresults_serviced_organisation_id_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "update dqs_observationresults dobs"
                " set serviced_organisation_vehicle_journey_id = svj.id"
                " from transmodel_servicedorganisationvehiclejourney svj"
                " where dobs.serviced_organisation_id_id = svj.serviced_organisation_id"
                " and dobs.vehicle_journey_id = svj.vehicle_journey_id "
            )
        )
    ]
