# Generated by Django 4.2.14 on 2024-10-25 07:18

from django.db import migrations, models


def remove_field_if_exists(apps, schema_editor):
    ObservationResultModel = apps.get_model("dqs", "observationresults")
    if "serviced_organisation_id" in [
        f.name for f in ObservationResultModel._meta.get_fields()
    ]:
        schema_editor.remove_field(
            ObservationResultModel,
            ObservationResultModel._meta.get_field("serviced_organisation_id"),
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "dqs",
            "0011_update_dqs_observationresults_serviced_organisation_vehicle_journey_id",
        ),
    ]

    operations = [
        migrations.RunPython(remove_field_if_exists),
    ]
