# Generated by Django 4.2.14 on 2024-10-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dqs",
            "0012_remove_dqs_observationresults_serviced_organisation_vehicle_journey_id_if_exists",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observationresults",
            name="serviced_organisation_id",
        ),
    ]
