# Generated by Django 4.1.13 on 2024-05-14 15:51

from django.db import migrations
from transit_odp.data_quality_service.constants import CHECKS_DATA


def insert_updated_data(apps, schema_editor):
    Checks = apps.get_model("data_quality_service", "Checks")
    for entry in CHECKS_DATA:
        Checks.objects.create(**entry)


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality_service", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_updated_data),
    ]