# Generated by Django 4.1.13 on 2024-05-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality_service", "0002_auto_20240514_1651"),
    ]

    operations = [
        migrations.AddField(
            model_name="checks",
            name="queue_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
