# Generated by Django 2.2.12 on 2020-07-02 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisation", "0034_datasetmetadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaresMetadata",
            fields=[
                (
                    "datasetmetadata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="organisation.DatasetMetadata",
                    ),
                ),
                ("num_of_fare_zones", models.PositiveIntegerField()),
                ("num_of_lines", models.PositiveIntegerField()),
                ("num_of_sales_offer_packages", models.PositiveIntegerField()),
                ("num_of_fare_products", models.PositiveIntegerField()),
                ("num_of_user_profiles", models.PositiveIntegerField()),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
            ],
            bases=("organisation.datasetmetadata",),
        ),
    ]
