# Generated by Django 2.2.13 on 2020-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("naptan", "0002_auto_20191124_1907"),
        ("fares", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faresmetadata",
            name="stops",
            field=models.ManyToManyField(
                related_name="faresmetadata", to="naptan.StopPoint"
            ),
        ),
    ]
