# Generated by Django 2.2.12 on 2020-09-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fares", "0002_faresmetadata_stops"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faresmetadata",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faresmetadata",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
