# Generated by Django 3.2.16 on 2022-12-15 17:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fares", "0003_auto_20200923_1223"),
    ]

    operations = [
        migrations.AddField(
            model_name="faresmetadata",
            name="atco_area",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="fares_valid_from",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="fares_valid_to",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="line_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="line_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="national_operator_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="product_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="product_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="tariff_basis",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="user_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="xml_file_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="FaresDataCatalogueMetaData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xml_file_name", models.CharField(blank=True, max_length=255)),
                ("valid_from", models.DateField(max_length=100, null=True)),
                ("valid_to", models.DateField(max_length=100, null=True)),
                (
                    "national_operator_code",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "line_id",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "line_name",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "atco_area",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "tariff_basis",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "product_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "product_name",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "user_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "fares_metadata_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fares.faresmetadata",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="fares_data_catalogue_metadata",
            field=models.ManyToManyField(
                related_name="faresmetadata", to="fares.FaresDataCatalogueMetaData"
            ),
        ),
    ]
