# Generated by Django 3.2.16 on 2023-01-05 12:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fares", "0003_auto_20200923_1223"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCatalogueMetaData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xml_file_name", models.CharField(blank=True, max_length=255)),
                ("valid_from", models.DateField(max_length=100, null=True)),
                ("valid_to", models.DateField(max_length=100, null=True)),
                (
                    "national_operator_code",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=255),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "line_id",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "line_name",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "atco_area",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), null=True, size=None
                    ),
                ),
                (
                    "tariff_basis",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "product_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "product_name",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "user_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "fares_metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datacatalogue",
                        to="fares.faresmetadata",
                    ),
                ),
            ],
        ),
    ]
