# Generated by Django 3.2.16 on 2022-12-13 16:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fares", "0003_auto_20200923_1223"),
    ]

    operations = [
        migrations.AddField(
            model_name="faresmetadata",
            name="atco_area",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255, null=True),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="fares_valid_from",
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="fares_valid_to",
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="line_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255, null=True),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="line_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="national_operator_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255, null=True),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="product_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="product_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="tariff_basis",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="user_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100, null=True),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="xml_file_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255, null=True),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
