# Generated by Django 3.2.16 on 2023-01-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fares", "0004_datacataloguemetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="faresmetadata",
            name="num_of_pass_products",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="faresmetadata",
            name="num_of_trip_products",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
