#!/usr/bin/env sh

set -o errexit
set -o nounset

python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn config.wsgi -b 0.0.0.0:5000 --chdir=/app --log-file=- --error-logfile=- --log-level debug --capture-output --forwarded-allow-ips="*"
#gunicorn config.wsgi -w 8  -b 0.0.0.0:8000 --forwarded-allow-ips="*"
