- rule:
    name: AS01
    message: Accessability image should have alt attribute.
    flags: re.DOTALL
    patterns:
      - <img:not([alt])>
- rule:
    name: AS02
    message: Accessability validate whether a video tag has closed captioning.
    flags: re.DOTALL
    patterns:
      - <video[^>]*?captions=["'][^"']*["'][^>]*>
# - rule:
#     name: AS03
#     message: Accessability To validate whether HTML content adheres to proper structure.
#     flags: re.DOTALL
#     patterns:
#       - <[^>]+>
