# Generated by Django 3.2.13 on 2022-09-26 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naptan", "0002_auto_20191124_1907"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoppoint",
            name="stop_areas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=list,
                size=None,
            ),
        ),
    ]
