# Generated by Django 3.2.20 on 2023-12-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("otc", "0012_remove_localauthority_atco_code"),
        ("naptan", "0004_adminarea_ui_lta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminarea",
            name="ui_lta",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="naptan_ui_lta_records",
                to="otc.uilta",
            ),
        ),
    ]
