# Generated by Django 4.1.13 on 2024-01-09 10:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("naptan", "0005_alter_adminarea_ui_lta"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoppoint",
            name="bus_stop_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stoppoint",
            name="stop_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="FlexibleZone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_number", models.IntegerField()),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "naptan_stoppoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="naptan.stoppoint",
                    ),
                ),
            ],
            options={
                "ordering": ("naptan_stoppoint", "sequence_number"),
            },
        ),
    ]
