# Generated by Django 4.2.9 on 2024-01-24 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("naptan", "0006_stoppoint_bus_stop_type_stoppoint_stop_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexiblezone",
            name="naptan_stoppoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flexible_zones",
                to="naptan.stoppoint",
            ),
        ),
        migrations.AddConstraint(
            model_name="flexiblezone",
            constraint=models.UniqueConstraint(
                fields=("naptan_stoppoint", "sequence_number"),
                name="unique_flexible_zone",
            ),
        ),
    ]
