TYPE_OF_FRAME_REF_SUBSTRING = ["UK_PI_LINE_FARE_OFFER", "UK_PI_NETWORK_OFFER"]
FAREFRAME_TYPE_OF_FRAME_REF_SUBSTRING = ["UK_PI_FARE_PRODUCT", "UK_PI_FARE_PRICE"]
TYPE_OF_TARIFF_REF_STRING = [
    "fxc:Distance_kilometers",
    "fxc:flat",
    "fxc:section",
    "fxc:point_to_point",
    "fxc:zone_to_zone",
    "fxc:zonal",
    "fxc:banded",
    "fxc:stored_value",
    "fxc:discount",
    "fxc:multitrip",
]
TYPE_OF_FRAME_REF_FARE_ZONES_SUBSTRING = "UK_PI_FARE_NETWORK"
TYPE_OF_FRAME_REF_SERVICE_FRAME_SUBSTRING = "UK_PI_NETWORK"
TYPE_OF_FRAME_REF_FARE_PRODUCT_SUBSTRING = "UK_PI_FARE_PRODUCT"
TYPE_OF_FRAME_FARE_TABLES_REF_SUBSTRING = "UK_PI_FARE_PRICE"
TYPE_OF_FRAME_METADATA_SUBSTRING = "METADATA"
FARE_STRUCTURE_ELEMENT_DURATION_REF = "fxc:durations"
FARE_STRUCTURE_ELEMENT_ACCESS_REF = "fxc:access"
FARE_STRUCTURE_ACCESS_RIGHT_REF = "fxc:can_access"
FARE_STRUCTURE_ELEMENT_ELIGIBILITY_REF = "fxc:eligibility"
FARE_STRUCTURE_ACCESS_RIGHT_ELIGIBILITY_REF = "fxc:eligible"
FARE_STRUCTURE_ELEMENT_TRAVEL_REF = "fxc:travel_conditions"
FARE_STRUCTURE_ACCESS_RIGHT_TRAVEL_REF = "fxc:condition_of_use"
ORG_OPERATOR_ID_SUBSTRING = "noc:"
STOP_POINT_ID_SUBSTRING = "atco:"
LENGTH_OF_OPERATOR = 8
LENGTH_OF_PUBLIC_CODE = 4
NAMESPACE = {"x": "http://www.netex.org.uk/netex"}
