export interface CatalogueField {
  field: string;
  definition: string;
}

// Mirrors transit_odp/organisation/csv/overall.py FEATURE_FLAG_OVERALL_COLUMN_MAP
export const OVERALL_CATALOGUE_FIELDS: CatalogueField[] = [
  { field: 'Operator', definition: 'The name of the operator/publisher providing data on BODS.' },
  { field: 'Operator ID', definition: 'The internal BODS generated ID of the operator/publisher providing data on BODS.' },
  { field: 'Profile NOCs', definition: 'The National Operator Codes for the particular publisher as extracted from their BODS profile.' },
  { field: 'Data Type', definition: 'The type of data being published.' },
  { field: 'Status', definition: 'The publication status of the data set/feed.' },
  { field: 'Last Updated', definition: 'The date that the data set/feed was last updated on BODS.' },
  { field: 'File Name', definition: 'The exact name of the file provided to BODS. This is usually generated by the publisher or their supplier' },
  { field: 'XML File Name', definition: 'The value of the FileName attribute in the TransXChange or NeTEx file.' },
  { field: 'Data Set/Feed Name', definition: 'The internal BODS generated data set name given for a particular data set.' },
  { field: 'Data ID', definition: 'The internal BODS generated ID of the data set / feed provided to BODS.' },
  { field: 'Mode', definition: 'The mode of transport as extracted from the TransXChange file they provided.' },
  { field: 'National Operator Code', definition: 'The National Operator Code(s) for the particular publisher as extracted from the TransXChange or NeTEx file they provided.' },
  { field: 'Service Code', definition: 'The ServiceCode for the particular publisher as extracted from the TransXChange file they provided.' },
  { field: 'Line Name', definition: 'The line name(s) for the particular publisher as extracted from the TransXChange or NeTEx file they provided.' },
  { field: 'Licence Number', definition: 'The License number(s) as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'Public Use Flag', definition: 'The Public Use Flag element as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'Revision Number', definition: 'The service revision number date as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'Operating Period Start Date', definition: 'The operating period start date as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'Operating Period End Date', definition: 'The operating period end date as extracted from the files provided by the operator/publisher to BODS.' },
  { field: '% AVL to Timetables feed matching score', definition: 'The latest score for the active AVL feed this row belongs to (Data ID).' },
  { field: 'Latest matching report URL', definition: 'This will be the same report url as the AVL data feed page report url from the dataset review page.' },
];

// Mirrors transit_odp/timetables/csv.py TIMETABLE_COLUMN_MAP
export const TIMETABLE_CATALOGUE_FIELDS: CatalogueField[] = [
  { field: 'XML:Service Code', definition: 'The ServiceCode(s) as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'XML:Line Name', definition: 'The line name(s) as extracted from the files provided by the operator/publisher to BODS.' },
  {
    field: 'Requires Attention',
    definition:
      'No:<br />Default state for correctly published services, will be “No” unless any of the logic below is met.<br /><br />' +
      'Yes:<br />Yes If OTC status = Registered and Scope Status = In scope and Seasonal Status ≠ Out of season and Published Status = Unpublished.<br />' +
      'Yes if OTC status = Registered and Scope Status = In scope and Seasonal Status ≠ Out of season and Published Status = Published and Timeliness Status ≠ Up to date.',
  },
  {
    field: 'Published Status',
    definition: 'Published: Published to BODS by an Operator/Agent.<br /><br />Unpublished: Not published to BODS by an Operator/Agent.',
  },
  {
    field: 'OTC Status',
    definition: 'Registered: Registered and not cancelled within the OTC database.<br /><br />Unregistered: Not Registered within the OTC.',
  },
  {
    field: 'Scope Status',
    definition:
      'In scope: Default status for services registered with the OTC and other enhanced partnerships.<br /><br />' +
      'Out of Scope: Service code has been marked as exempt by the DVSA or the BODS team.',
  },
  {
    field: 'Seasonal Status',
    definition:
      'In season: Service code has been marked as seasonal by the operator or their agent and todays date falls within the relevant date range for that service code.<br /><br />' +
      'Out of Season: Service code has been marked as seasonal by the operator or their agent and todays date falls outside the relevant date range for that service code.<br /><br />' +
      'Not Seasonal: Default status for published or unpublished services to BODS.<br />Assumed Not seasonal unless service code has been marked with a date range within the seasonal services flow.',
  },
  {
    field: 'Timeliness Status',
    definition:
      'Up to date: Default status for service codes published to BODS.<br /><br />' +
      'Timeliness checks are evaluated in this order:<br /><br />' +
      "1) OTC Variation not published:<br />If 'XML:Last modified date' is earlier than 'Date OTC variation needs to be published'<br />and<br />'Date OTC variation needs to be published' is earlier than today's date.<br />and<br />" +
      'No associated data has been published.<br />' +
      'NB there are two association methods:<br />Method 1:<br />Data for that service code has been updated within 70 days before the OTC variation effective date.<br />Method 2:<br />' +
      "Data for that service code has been updated with a 'XML:Operating Period Start Date' which equals OTC variation effective date.<br /><br />" +
      "2) 42 day look ahead is incomplete:<br />If not out of date due to 'OTC variation not published'<br />and<br />'XML:Operating Period End Date' is earlier than 'Date for complete 42 day look ahead'.<br /><br />" +
      "3) Service hasn't been updated within a year:<br />If not out of date due to '42 day lookahead is incomplete' or 'OTC variation not published'<br />and<br />'Date at which data is 1 year old' is earlier than today's date.",
  },
  { field: 'Organisation Name', definition: 'The name of the operator/publisher providing data on BODS.' },
  { field: 'Data set ID', definition: 'The internal BODS generated ID of the dataset that contains the data for this row.' },
  { field: 'Date OTC variation needs to be published', definition: 'OTC:Effective date from timetable data catalogue minus 42 days.' },
  { field: 'Date for complete 42 day look ahead', definition: "Today's date + 42 days." },
  { field: 'Date when data is over 1 year old', definition: "'XML:Last Modified date' from timetable data catalogue plus 12 months." },
  { field: 'Date seasonal service should be published', definition: 'If Seasonal Start Date is present, then Seasonal Start Date minus 42 days, else null.' },
  { field: 'Seasonal Start Date', definition: 'If service has been assigned a date range from within the seasonal services flow, then take start date, else null.' },
  { field: 'Seasonal End Date', definition: 'If service has been assigned a date range from within the seasonal services flow, then take end date, else null.' },
  { field: 'XML:Filename', definition: 'The exact name of the file provided to BODS. This is usually generated by the publisher or their supplier.' },
  { field: 'XML:Last Modified Date', definition: 'Date of last modified file within the service codes dataset.' },
  { field: 'XML:National Operator Code', definition: 'The National Operator Code(s) as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'XML:Licence Number', definition: 'The License number(s) as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'XML:Public Use Flag', definition: 'The Public Use Flag element as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'XML:Revision Number', definition: 'The service revision number date as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'XML:Operating Period Start Date', definition: 'The operating period start date as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'XML:Operating Period End Date', definition: 'The operating period end date as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'OTC:Origin', definition: 'The origin element as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'OTC:Destination', definition: 'The destination element as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'OTC:Operator ID', definition: 'The operator ID element as extracted from the OTC database.' },
  { field: 'OTC:Operator Name', definition: 'The operator name element as extracted from the OTC database.' },
  { field: 'OTC:Address', definition: 'The address as extracted from the OTC database.' },
  { field: 'OTC:Licence Number', definition: 'The licence number element as extracted from the OTC database.' },
  { field: 'OTC:Licence Status', definition: 'The licence status element as extracted from the OTC database.' },
  { field: 'OTC:Registration Number', definition: 'The registration number element as extracted from the OTC database.' },
  { field: 'OTC:Service Type Description', definition: 'The service type description element as extracted from the OTC database.' },
  { field: 'OTC:Variation Number', definition: 'The variation number element as extracted from the OTC database.' },
  { field: 'OTC:Service Number', definition: 'The service number element as extracted from the OTC database.' },
  { field: 'OTC:Start Point', definition: 'The start point element as extracted from the OTC database.' },
  { field: 'OTC:Finish Point', definition: 'The finish point element as extracted from the OTC database.' },
  { field: 'OTC:Via', definition: 'The via element as extracted from the OTC database.' },
  { field: 'OTC:Granted Date', definition: 'The granted date element as extracted from the OTC database.' },
  { field: 'OTC:Expiry Date', definition: 'The expiry date element as extracted from the OTC database.' },
  { field: 'OTC:Effective Date', definition: 'The effective date element as extracted from the OTC database.' },
  { field: 'OTC:Received Date', definition: 'The received date element as extracted from the OTC database.' },
  { field: 'OTC:Service Type Other Details', definition: 'The service type other details element as extracted from the OTC database.' },
  { field: 'Traveline Region', definition: 'The Traveline Region details element as extracted from the OTC database.' },
  { field: 'Local Transport Authority', definition: 'The Local Transport Authority element as extracted from the OTC database.' },
];

// Mirrors transit_odp/fares_validator/csv.py FARES_DATA_COLUMN_MAP
export const FARES_CATALOGUE_FIELDS: CatalogueField[] = [
  { field: 'Dataset ID', definition: 'The internal BODS generated ID of the operator/publisher providing data on BODS.' },
  { field: 'XML file name', definition: 'The exact name of the file provided to BODS. This is usually generated by the publisher or their supplier.' },
  { field: 'Organisation Name', definition: 'The name of the operator/publisher providing data on BODS.' },
  { field: 'National Operator Code', definition: 'The National Operator Code(s) for the particular publisher as extracted from the NeTEx file they provided.' },
  { field: 'Operator ID', definition: 'The internal BODS generated ID of the operator/publisher providing data on BODS.' },
  { field: 'BODS Compliant', definition: 'The validation status and format of the files provided by the operator/publisher to BODS.' },
  { field: 'Last updated date', definition: 'The date that the data set/feed was last updated on BODS.' },
  { field: 'Valid from', definition: 'The operating period start date as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'Valid to', definition: 'The operating period end date as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'Line ids', definition: 'The Line id(s) as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'Line Name', definition: 'The line name(s) as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'ATCO Area', definition: 'The ATCO Area (s) extracted from the ScheduledStopPoints in the files provided by the operator/publisher to BODS.' },
  { field: 'TariffBasis', definition: 'The TariffBasis element as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'ProductType', definition: 'The ProductType element as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'ProductName', definition: 'The Name element within PreassignedFareProduct as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'UserType', definition: 'The origin element as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'Multioperator', definition: 'Status derived from comparing the BODS organisation of publisher and the National Operator Codes extracted from the files provided by the operator/publisher to BODS.' },
];

// Mirrors transit_odp/disruptions/csv/catalogue.py DISRUPTIONS_COLUMN_MAP
export const DISRUPTIONS_CATALOGUE_FIELDS: CatalogueField[] = [
  { field: 'Organisation', definition: 'The name of the organisation publishing the disruptions data.' },
  { field: 'Situation Number', definition: 'The internal BODS generated ID of the disruption.' },
  { field: 'Validity Start Date', definition: 'The start date of the disruption provided by the publisher to BODS.' },
  { field: 'Validity End Date', definition: 'The end date of the disruption provided by the publisher to BODS.' },
  { field: 'Publication Start Date', definition: 'The start date of the publication window for the disruption provided by the publisher to BODS.' },
  { field: 'Publication End Date', definition: 'The end date of the publication window for the disruption provided by the publisher to BODS.' },
  { field: 'Reason', definition: 'The reason for the disruption provided by the publisher to BODS.' },
  { field: 'Planned', definition: 'The planned or unplanned nature of the disruption provided to the publisher to BODS.' },
  { field: 'Modes Affected', definition: 'The modes of public transport affected by the disruption.' },
  { field: 'Operators Affected', definition: 'The operators of services affected by the disruption.' },
  { field: 'Services Affected', definition: 'The total number of services affected by the disruption.' },
  { field: 'Stops Affected', definition: 'The total number of stops affected by the disruption.' },
];

// Mirrors transit_odp/organisation/csv/organisation.py FEATURE_FLAG_ORG_COLUMN_MAP
export const ORGANISATIONS_CATALOGUE_FIELDS: CatalogueField[] = [
  { field: 'Name', definition: 'The name of the operator/publisher providing data on BODS' },
  {
    field: 'Status',
    definition:
      "The registration status of the operator/publisher on BODS. 'Active' are signed up on BODS, 'Inactive' no longer have functioning accounts on BODS, 'Pending Invite' still haven't signed up and 'Not yet invited' have been added to BODS but not yet invited to complete the full sign up procedure",
  },
  { field: 'Date Invite Accepted', definition: 'The date at which the operator/publisher accepted their invite and signed up' },
  { field: 'Organisation creation date', definition: 'The date at which the Operator/publisher organisation are added to BODS which may or may not be the same date as the invited date.' },
  { field: 'Date Invited', definition: 'The date at which they were originally invited to sign up to BODS' },
  { field: 'Last Log-In', definition: 'The last time there was activity for the operator/publisher on BODS.' },
  {
    field: 'Permit Holder',
    definition:
      "The permit status as declared by operator/publisher in the Organisation profile section on BODS (Permit holder is 'Yes' if the user clicks the tickbox of 'I don't have a PSV license number')",
  },
  { field: 'National Operator Codes', definition: 'The National Operator Codes of the operator/ publisher as declared by them in the Organisation Profile section on BODS.' },
  { field: 'Licence Numbers', definition: 'The Licence number(s) of the operator/publisher as declared by them in the Organisation Profile section on BODS.' },
  {
    field: 'Number of Licences',
    definition:
      'The total count of services of the operator/publisher as declared by them in the Organisation Profile section on BODS. This informs us to understand the total number of licence numbers the organisation is representing.',
  },
  { field: 'Unregistered Services', definition: "The total number of unregistered services (UZ declared in ServiceCode field) are published in total by the operator/publisher to BODS." },
  {
    field: 'OTC Registered Services',
    definition:
      'The total count of services of the operator/publisher as extracted from the database of the Office of the Traffic Commissioner (OTC). This informs us to understand the total number of services expected to be published from the licences associated in the organisational profile.',
  },
  { field: 'Out of scope services(exempted)', definition: 'The total number of registered services that have been marked as exempt from publishing to BODS by the DVSA/DfT admin user.' },
  { field: 'Registered Services in scope(for BODS)', definition: 'The total number of in scope, registered services for the organisation that require data in BODS' },
  { field: 'Registered Services Published', definition: 'The total number of registered services that an organisation has published.' },
  { field: 'Compliant Registered Services Published', definition: 'The total number of compliant, in scope, registered services are published in total by the operator/publisher to BODS.' },
  { field: '% Compliant Registered Services Published', definition: "The percentage of an organisation's in scope, registered services that are PTI compliant." },
  {
    field: 'Number of School or Works Services',
    definition:
      "The total count of school or works services of the operator/publisher as extracted from the database of the Office of the Traffic Commissioner (OTC). This informs us to understand the total number of services expected to be published from the licences associated in the organisational profile that are 'School or Works'.",
  },
  {
    field: 'School or Works Services Subsidised',
    definition:
      "The total count of school or works services that are subsidised for the operator/publisher as extracted from the database of the Office of the Traffic Commissioner (OTC). This informs us to understand the total number of services expected to be published from the licences associated in the organisational profile that are 'School or Works' and are fully subsidised (Yes).",
  },
  {
    field: 'School or Works Services Subsidised In Part',
    definition:
      "The total count of school or works services that are subsidised in part for the operator/publisher as extracted from the database of the Office of the Traffic Commissioner (OTC). This informs us to understand the total number of services expected to be published from the licences associated in the organisational profile that are 'School or Works' and are in part subsidised (In Part).",
  },
  {
    field: 'Flexible Registration',
    definition:
      "The total count of flexible services for the operator/publisher as extracted from the database of the Office of the Traffic Commissioner (OTC). This informs us to understand the total number of services expected to be published from the licences associated in the organisational profile that are 'Flexible' services, so we can prepare organisations for this technical implementation.",
  },
  { field: 'Number of Published Services with Valid Operating Dates', definition: 'The total number of services published on BODS that have a valid operating period today.' },
  {
    field: 'Additional Published Services with Future Start Date',
    definition:
      'The total number of additional published services that have future start dates on BODS. This informs us to understand the additional number of new services codes that will become valid in the future, which is just a difference to the total already provided, to give an indicator to services that are published but not valid now.',
  },
  { field: 'Number of Published Timetable Datasets', definition: 'The total number of published timetables datasets provided by the operator/publisher to BODS.' },
  { field: 'Number of Published AVL Datafeeds', definition: 'The total number of published location data feeds provided by the operator/publisher to BODS.' },
  { field: 'Number of Published Fare Datasets', definition: 'The total number of published fares datasets provided by the operator/publisher to BODS.' },
  { field: '% Compliant Published Fare Datasets', definition: "The percentage of an organisation's published fare datasets that are BODS compliant." },
  { field: 'Number of Pass Products', definition: 'The total number of pass products as extracted from the files provided by the operator/publisher to BODS.' },
  { field: 'Number of Trip Products', definition: 'The total number of trip limited products as extracted from the files provided by the operator/publisher to BODS.' },
  { field: '% Operator overall AVL to Timetables matching score', definition: "The overall score for an operator as per 'Review my location data' blue dashboard for an operator." },
  { field: 'Archived matching reports URL', definition: "The same archived reports url as the 'Review my location data' blue dashboard for an operator in Download all archived matching reports." },
];

// Mirrors transit_odp/avl/csv/catalogue.py AVL_COLUMN_MAP
export const LOCATION_CATALOGUE_FIELDS: CatalogueField[] = [
  { field: 'Organisation Name', definition: 'The name of the operator/publisher providing data on BODS.' },
  { field: 'Datafeed ID', definition: 'The internal BODS generated ID of the operator/publisher providing data on BODS.' },
  { field: '% AVL to Timetables feed matching score', definition: 'This will be the latest score for the AVL feed this row belongs to (Data ID).' },
  { field: 'Latest matching report URL', definition: 'This will be the same report url as the AVL data feed page report url from the dataset review page.' },
];

// Mirrors transit_odp/browse/exports.py OPERATOR_NOC_MAP
export const OPERATOR_NOC_CATALOGUE_FIELDS: CatalogueField[] = [
  { field: 'Operator', definition: 'The name of the operator on BODS.' },
  { field: 'NOC', definition: 'The National Operator Code (NOC) that is associated with that operator on BODS.' },
];
