# Generated by Django 2.2.5 on 2019-09-30 08:49

import django.db.models.deletion
import django_extensions.db.fields
import django_fsm
from django.db import migrations, models

import transit_odp.common.validators
import transit_odp.publish.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [("django_celery_results", "0004_auto_20190516_0412")]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DatasetRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "upload_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        validators=[
                            transit_odp.publish.validators.validate_file_extension
                        ],
                        verbose_name="Name of the uploaded file, if any",
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("indexing", "Indexing"),
                            ("error", "Error"),
                            ("success", "Success"),
                            ("expiring", "Soon to expire"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[transit_odp.common.validators.validate_profanity],
                        verbose_name="Feed name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255,
                        validators=[transit_odp.common.validators.validate_profanity],
                        verbose_name="Any description for the feed",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        default="First publication",
                        max_length=255,
                        validators=[transit_odp.common.validators.validate_profanity],
                        verbose_name="Any comments for the feed",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Whether the feed is published or not"
                    ),
                ),
                (
                    "url_link",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        verbose_name="URL link to feed, if any",
                    ),
                ),
                (
                    "num_of_lines",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Lines"
                    ),
                ),
                (
                    "num_of_operators",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Number of operators in the feed",
                    ),
                ),
                (
                    "line_names",
                    models.CharField(blank=True, max_length=8096, null=True),
                ),
                ("transxchange_version", models.CharField(blank=True, max_length=8)),
                ("imported", models.DateTimeField(blank=True, null=True)),
                (
                    "bounding_box",
                    models.CharField(blank=True, max_length=8096, null=True),
                ),
                (
                    "publisher_creation_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "publisher_modified_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "first_expiring_service",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiry Date"
                    ),
                ),
                (
                    "last_expiring_service",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiry Date"
                    ),
                ),
                (
                    "first_service_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Date"
                    ),
                ),
                (
                    "num_of_bus_stops",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="BusStops"
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedErrors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("severe", "Severe"), ("minor", "Minor")],
                        max_length=255,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("xml", "Xml"),
                            ("zip", "Zip"),
                            ("naptan", "Naptan"),
                            ("unknown", "Unknown"),
                            ("data", "Data"),
                            ("availability", "Availability"),
                        ],
                        max_length=255,
                        verbose_name="Category",
                    ),
                ),
                ("description", models.CharField(max_length=8096)),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Name of Organisation"
                    ),
                ),
                (
                    "noc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="National Operator Code"
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedTaskResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("progress", models.IntegerField(verbose_name="Feed Progress")),
                (
                    "revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_result",
                        to="organisation.DatasetRevision",
                    ),
                ),
                (
                    "task_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_result",
                        to="django_celery_results.TaskResult",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedSubscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_subscriber",
                        to="organisation.Dataset",
                    ),
                ),
            ],
        ),
    ]
