# Generated by Django 2.2.5 on 2019-10-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organisation", "0002_auto_20190930_0949")]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Name of Organisation"
            ),
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(fields=["name"], name="organisation_name_idx"),
        ),
    ]
