# Generated by Django 2.2.5 on 2019-10-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organisation", "0005_auto_20191003_1138")]

    operations = [
        migrations.RemoveField(model_name="feedtaskresult", name="revision"),
        migrations.RemoveField(model_name="feedtaskresult", name="task_result"),
        migrations.RemoveField(model_name="datasetrevision", name="task_progress"),
        migrations.AlterField(
            model_name="datasetsubscription",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="organisation.Dataset"
            ),
        ),
        migrations.DeleteModel(name="FeedErrors"),
        migrations.DeleteModel(name="FeedTaskResult"),
    ]
