# Generated by Django 2.2.5 on 2019-10-04 11:08
import logging

from django.db import migrations
from django.db.models import Count

logger = logging.getLogger(__name__)


def delete_duplicates(apps, schema_editor):
    logger.info("Deleting datasets with duplicate names")
    Dataset = apps.get_model("organisation", "Dataset")
    DatasetRevision = apps.get_model("organisation", "DatasetRevision")

    duplicates = (
        DatasetRevision.objects.order_by("name")
        .values("name")
        .annotate(count=Count("name"))
        .filter(count__gt=1)
        .values("name")
    )

    qs = Dataset.objects.filter(revisions__name__in=duplicates)
    logger.info(f"Deleting {len(qs)} datasets")
    qs.delete()


class Migration(migrations.Migration):

    dependencies = [("organisation", "0006_auto_20191003_1254")]

    operations = [
        migrations.RunPython(
            delete_duplicates, migrations.RunPython.noop, elidable=True
        )
    ]
