# Generated by Django 2.2.5 on 2019-10-04 11:09

from django.db import migrations, models

import transit_odp.common.validators


class Migration(migrations.Migration):
    dependencies = [("organisation", "0007_auto_20191004_1208")]

    operations = [
        migrations.AlterField(
            model_name="datasetrevision",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[transit_odp.common.validators.validate_profanity],
                verbose_name="Feed name",
            ),
        )
    ]
