# Generated by Django 2.2.5 on 2019-10-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organisation", "0008_auto_20191004_1209")]

    operations = [
        migrations.AddField(
            model_name="datasetrevision",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The time when this change was published",
                null=True,
            ),
        )
    ]
