# Generated by Django 2.2.6 on 2019-10-22 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organisation", "0010_auto_20191009_0924")]

    operations = [
        migrations.CreateModel(
            name="OperatorCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_code",
                    models.CharField(
                        max_length=20, verbose_name="National Operator Code"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisation.Organisation",
                    ),
                ),
            ],
        )
    ]
