# Generated by Django 2.2.6 on 2019-10-22 14:21
import logging

from django.db import migrations

logger = logging.getLogger(__name__)

# Removed as migrations fail on Staging due to empty/repeated nocs
# def fill_operator_codes(apps, schema_editor):
#     logger.info("Populating operator_code field for OperatorCode model")
#     Organisation = apps.get_model("organisation", "Organisation")
#     OperatorCode = apps.get_model("organisation", "OperatorCode")
#
#     for organisation in Organisation.objects.all():
#         OperatorCode.objects.create(
#             operator_code=organisation.noc, organisation=organisation
#         )
#
#     logger.info(f"operator_code's updated")


class Migration(migrations.Migration):
    dependencies = [("organisation", "0011_operatorcode")]

    operations = [
        # migrations.RunPython(
        #     fill_operator_codes, migrations.RunPython.noop, elidable=True
        # )
    ]
