# Generated by Django 2.2.6 on 2019-10-22 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("organisation", "0012_auto_20191022_1521")]

    operations = [migrations.RemoveField(model_name="organisation", name="noc")]
