# Generated by Django 2.2.6 on 2019-10-22 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organisation", "0013_remove_organisation_noc")]

    operations = [
        migrations.AlterField(
            model_name="operatorcode",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operator_codes",
                to="organisation.Organisation",
            ),
        )
    ]
