# Generated by Django 2.2.6 on 2019-10-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organisation", "0014_auto_20191022_1654")]

    operations = [
        migrations.RenameField(
            model_name="operatorcode", old_name="operator_code", new_name="noc"
        ),
        migrations.AlterField(
            model_name="operatorcode",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nocs",
                to="organisation.Organisation",
            ),
        ),
    ]
