# Generated by Django 2.2.6 on 2019-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("organisation", "0015_auto_20191023_1535")]

    operations = [
        migrations.AlterField(
            model_name="operatorcode",
            name="noc",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="National Operator Code"
            ),
        )
    ]
