# Generated by Django 2.2.6 on 2019-10-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organisation", "0016_auto_20191023_1535")]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="short_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Organisation Short Name"
            ),
        )
    ]
