# Generated by Django 2.2.7 on 2019-11-14 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0019_auto_20191024_1431"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasetrevision",
            name="line_names",
        ),
    ]
