# Generated by Django 2.2.7 on 2019-11-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0021_auto_20191127_0045"),
        ("organisation", "0021_auto_20191128_1024"),
    ]

    operations = []
