# Generated by Django 2.2.9 on 2020-01-27 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisation", "0023_auto_20200107_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="key_contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="key_organisation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
