# Generated by Django 2.2.9 on 2020-02-03 15:15

from django.db import migrations, models

import transit_odp.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0023_auto_20200107_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetrevision",
            name="comment",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[transit_odp.common.validators.validate_profanity],
                verbose_name="Any comments for the feed",
            ),
        ),
    ]
