# Generated by Django 2.2.9 on 2020-02-03 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0024_organisation_key_contact"),
        ("organisation", "0024_auto_20200203_1515"),
    ]

    operations = []
