# Generated by Django 2.2.9 on 2020-02-04 09:23
import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def fill_is_active(apps, schema_editor):
    logger.info("Populating is_active field for existing organisations in DB with True")
    Organisation = apps.get_model("organisation", "Organisation")

    # Get all existing organisations from DB
    qs = Organisation.objects.all()
    logger.info(f"Populating {len(qs)} organisations")

    qs.update(is_active=True)
    logger.info(f"Organisations updated")


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0025_merge_20200203_1611"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="is_active",
            field=models.BooleanField(
                default=False, help_text="Whether the organisation is active or not"
            ),
        ),
        migrations.RunPython(fill_is_active, migrations.RunPython.noop, elidable=True),
    ]
