# Generated by Django 2.2.9 on 2020-02-11 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0027_dataset_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="contact",
            field=models.ForeignKey(
                help_text="This user will receive all notifications",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_datasets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
