# Generated by Django 2.2.9 on 2020-03-23 10:01

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models

import transit_odp.organisation.constants


class Migration(migrations.Migration):

    dependencies = [
        ("naptan", "0002_auto_20191124_1907"),
        ("organisation", "0028_auto_20200211_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="dataset_type",
            field=models.IntegerField(
                choices=[(1, "TIMETABLE"), (2, "AVL")],
                default=transit_odp.organisation.constants.DatasetType(1),
            ),
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="is_capability_request",
            field=models.NullBooleanField(
                verbose_name="Is the resource a capability request"
            ),
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="password",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Password required to access the resource, if any",
            ),
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="requestor_ref",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Requestor ref to access the resource, if any",
            ),
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="resource_type",
            field=models.IntegerField(
                choices=[(1, "TIMETABLE"), (2, "AVL")],
                default=transit_odp.organisation.constants.DatasetType(1),
            ),
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Username required to access the resource, if any",
            ),
        ),
        migrations.CreateModel(
            name="TimetableMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "num_of_lines",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Lines"
                    ),
                ),
                (
                    "num_of_operators",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Number of operators in the feed",
                    ),
                ),
                ("transxchange_version", models.CharField(blank=True, max_length=8)),
                ("imported", models.DateTimeField(blank=True, null=True)),
                (
                    "bounding_box",
                    models.CharField(blank=True, max_length=8096, null=True),
                ),
                (
                    "publisher_creation_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "publisher_modified_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "first_expiring_service",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiry Date"
                    ),
                ),
                (
                    "last_expiring_service",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiry Date"
                    ),
                ),
                (
                    "first_service_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Date"
                    ),
                ),
                (
                    "num_of_bus_stops",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="BusStops"
                    ),
                ),
                (
                    "admin_areas",
                    models.ManyToManyField(
                        related_name="resources", to="naptan.AdminArea"
                    ),
                ),
                (
                    "localities",
                    models.ManyToManyField(
                        related_name="resources", to="naptan.Locality"
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_resource",
                        to="organisation.DatasetRevision",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
