# Generated by Django 2.2.9 on 2020-03-23 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0029_auto_20200323_1001"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasetrevision",
            name="resource_type",
        ),
        migrations.DeleteModel(
            name="TimetableMetadata",
        ),
    ]
