# Generated by Django 2.2.12 on 2020-06-11 11:16

from django.db import migrations, models

import transit_odp.organisation.constants


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0032_dataset_avl_feed_last_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="dataset_type",
            field=models.IntegerField(
                choices=[(1, "TIMETABLE"), (2, "AVL"), (3, "FARES")],
                default=transit_odp.organisation.constants.DatasetType(1),
            ),
        ),
    ]
