# Generated by Django 2.2.12 on 2020-07-02 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0033_auto_20200611_1216"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_version", models.CharField(max_length=8)),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="organisation.DatasetRevision",
                    ),
                ),
            ],
        ),
    ]
