# Generated by Django 2.2.13 on 2020-08-18 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0034_datasetmetadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasetrevision",
            name="is_capability_request",
        ),
    ]
