# Generated by Django 2.2.13 on 2020-09-04 09:09
import logging

from django.db import migrations, models

import transit_odp.common.validators

logger = logging.getLogger(__name__)


def fill_short_desciption(apps, schema_editor):
    logger.info("Populating short_desciption field for existing revisions in DB")
    DatasetRevision = apps.get_model("organisation", "DatasetRevision")

    # Get all existing revisions from DB
    revisions = DatasetRevision.objects.all()
    logger.info(f"Populating {len(revisions)} revisions")

    for revision in revisions:
        revision.short_description = revision.description[:30]
        revision.save()
    logger.info(f"Dataset revisions updated")


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0035_remove_datasetrevision_is_capability_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetrevision",
            name="short_description",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[transit_odp.common.validators.validate_profanity],
                verbose_name="Short description for the feed",
            ),
        ),
        migrations.RunPython(
            fill_short_desciption, migrations.RunPython.noop, elidable=True
        ),
        migrations.AlterField(
            model_name="datasetrevision",
            name="short_description",
            field=models.CharField(
                max_length=30,
                validators=[transit_odp.common.validators.validate_profanity],
                verbose_name="Short description for the feed",
            ),
        ),
    ]
