# Generated by Django 2.2.13 on 2020-09-17 15:23
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def delete_expire_dataset_tasks(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0036_datasetrevision_short_description"),
    ]

    operations = [migrations.RunPython(delete_expire_dataset_tasks)]
