# Generated by Django 2.2.13 on 2021-02-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0037_delete_expire_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetrevision",
            name="num_of_timing_points",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Timing Points"
            ),
        ),
    ]
