# Generated by Django 2.2.19 on 2021-04-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0039_added_txc_attributes_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="txcfileattributes",
            name="modification",
            field=models.CharField(default="new", max_length=28),
            preserve_default=False,
        ),
    ]
