# Generated by Django 2.2.19 on 2021-04-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organisation",
            "0039_added_txc_attributes_model_squashed_0040_added_modification_field",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="txcfileattributes",
            name="modification",
            field=models.CharField(max_length=28),
        ),
    ]
