# Generated by Django 2.2.22 on 2021-05-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0040_field_modification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dataset",
            options={"get_latest_by": "modified"},
        ),
    ]
