# Generated by Django 2.2.23 on 2021-05-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0041_auto_20210506_1717"),
    ]

    operations = [
        migrations.AddField(
            model_name="txcfileattributes",
            name="national_operator_code",
            field=models.CharField(
                default="", max_length=100, verbose_name="National Operator Code"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="txcfileattributes",
            name="creation_datetime",
            field=models.DateTimeField(verbose_name="File Creation Datetime"),
        ),
        migrations.AlterField(
            model_name="txcfileattributes",
            name="filename",
            field=models.CharField(max_length=512, verbose_name="Filename"),
        ),
        migrations.AlterField(
            model_name="txcfileattributes",
            name="modification",
            field=models.CharField(max_length=28, verbose_name="Modification"),
        ),
        migrations.AlterField(
            model_name="txcfileattributes",
            name="modificaton_datetime",
            field=models.DateTimeField(verbose_name="File Modification Datetime"),
        ),
        migrations.AlterField(
            model_name="txcfileattributes",
            name="revision_number",
            field=models.IntegerField(verbose_name="File Revision Number"),
        ),
        migrations.AlterField(
            model_name="txcfileattributes",
            name="schema_version",
            field=models.CharField(
                max_length=10, verbose_name="TransXChange Schema Version"
            ),
        ),
        migrations.AlterField(
            model_name="txcfileattributes",
            name="service_code",
            field=models.CharField(max_length=100, verbose_name="Service Code"),
        ),
    ]
