# Generated by Django 2.2.23 on 2021-07-08 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0042_added_national_operator_code_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="txcfileattributes",
            old_name="modificaton_datetime",
            new_name="modification_datetime",
        ),
    ]
