# Generated by Django 2.2.23 on 2021-07-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0043_fixed_modification_datetime_typo"),
    ]

    operations = [
        migrations.AddField(
            model_name="txcfileattributes",
            name="licence_number",
            field=models.CharField(
                default="", max_length=56, verbose_name="Licence Number"
            ),
        ),
        migrations.AddField(
            model_name="txcfileattributes",
            name="operating_period_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Operating Period End Date"
            ),
        ),
        migrations.AddField(
            model_name="txcfileattributes",
            name="operating_period_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Operating Period Start Date"
            ),
        ),
        migrations.AddField(
            model_name="txcfileattributes",
            name="public_use",
            field=models.BooleanField(default=True),
        ),
    ]
