# Generated by Django 2.2.23 on 2021-07-13 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0044_added_txc_file_attribute_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="txcfileattributes",
            name="line_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True, max_length=255, verbose_name="Name of Lines"
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="txcfileattributes",
            name="public_use",
            field=models.BooleanField(
                default=True, verbose_name="Is the service for public use"
            ),
        ),
    ]
