# Generated by Django 2.2.23 on 2021-07-16 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0045_added_line_names_array_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="licence_required",
            field=models.BooleanField(
                default=None,
                null=True,
                verbose_name="Whether an organisation requires a PSV licence",
            ),
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=9, unique=True, verbose_name="PSV Licence Number"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licences",
                        to="organisation.Organisation",
                    ),
                ),
            ],
        ),
    ]
