# Generated by Django 3.1.13 on 2021-11-16 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0047_add_is_dummy_to_dataset"),
        ("organisation", "0047_add_stuck_revision_proxy"),
    ]

    operations = []
