# Generated by Django 3.1.13 on 2022-01-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0048_merge_20211116_1314"),
    ]

    operations = [
        migrations.AddField(
            model_name="txcfileattributes",
            name="destination",
            field=models.CharField(
                default="", max_length=512, verbose_name="Destination"
            ),
        ),
        migrations.AddField(
            model_name="txcfileattributes",
            name="origin",
            field=models.CharField(default="", max_length=512, verbose_name="Origin"),
        ),
    ]
