# Generated by Django 3.1.14 on 2022-04-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0050_convert_expired_to_inactive"),
    ]

    operations = [
        migrations.AddField(
            model_name="txcfileattributes",
            name="hash",
            field=models.CharField(
                default="", max_length=40, verbose_name="Hash of file"
            ),
        ),
    ]
