# Generated by Django 3.2.13 on 2022-06-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0052_add_consumer_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumerStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_breakdown",
                    models.FileField(
                        default=None,
                        upload_to="",
                        verbose_name="Monthly breakdown per dataset per day",
                    ),
                ),
                (
                    "weekly_unique_consumers",
                    models.IntegerField(
                        default=0,
                        verbose_name="Number of unique consumers in the last 7 days",
                    ),
                ),
                (
                    "weekly_downloads",
                    models.IntegerField(
                        default=0,
                        verbose_name="Number of direct downloads in the last 7 days",
                    ),
                ),
                (
                    "weekly_api_hits",
                    models.IntegerField(
                        default=0, verbose_name="Number of api hits in the last 7 days"
                    ),
                ),
                (
                    "organisation",
                    models.OneToOneField(
                        help_text="Operator",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="organisation.organisation",
                    ),
                ),
            ],
        ),
    ]
