# Generated by Django 3.2.13 on 2022-06-09 13:09
import logging

from django.db import migrations

from transit_odp.organisation.models import ConsumerStats as ConsumerStatsModel
from transit_odp.organisation.models import Organisation as OrganisationModel

logger = logging.getLogger(__name__)


def initialise_consumer_stats(apps, schema_editor):
    logger.info("Initialising organisation stats")
    Organisation: OrganisationModel = apps.get_model("organisation", "Organisation")
    ConsumerStats: ConsumerStatsModel = apps.get_model("organisation", "ConsumerStats")

    stats = []
    for organisation in Organisation.objects.order_by("id"):
        stats.append(ConsumerStats(organisation=organisation))

    ConsumerStats.objects.bulk_create(stats)


def rollback_consumer_stats(apps, schema_editor):
    ConsumerStats: ConsumerStatsModel = apps.get_model("organisation", "ConsumerStats")
    ConsumerStats.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0053_add_consumer_stats_to_organisations"),
    ]

    operations = [
        migrations.RunPython(initialise_consumer_stats, rollback_consumer_stats),
    ]
