# Generated by Django 3.2.13 on 2022-08-24 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0054_initialise_organisation_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="AVLComplianceCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Undergoing validation", "Undergoing validation"),
                            ("Partially compliant", "Partially compliant"),
                            ("Awaiting publisher review", "Awaiting publisher review"),
                            ("Compliant", "Compliant"),
                            ("Non-compliant", "Non-compliant"),
                            (
                                "Unavailable due to dormant feed",
                                "Unavailable due to dormant feed",
                            ),
                            ("Validation terminated", "Validation terminated"),
                        ],
                        default="Undergoing validation",
                        help_text="AVL compliance string",
                        max_length=50,
                    ),
                ),
                (
                    "dataset",
                    models.OneToOneField(
                        help_text="The data feed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avl_compliance_cached",
                        to="organisation.dataset",
                    ),
                ),
            ],
        ),
    ]
