# Generated by Django 3.2.13 on 2022-09-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0056_servicecodeexemption"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecodeexemption",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="servicecodeexemption",
            unique_together={("licence", "registration_code")},
        ),
    ]
