# Generated by Django 3.2.16 on 2023-01-13 16:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0057_add_unique_together_contraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonalService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "registration_code",
                    models.IntegerField(
                        help_text="The part of the service code after the licence prefix"
                    ),
                ),
                ("start", models.DateField(verbose_name="First day of season")),
                ("end", models.DateField(verbose_name="Last day of season")),
                (
                    "licence",
                    models.ForeignKey(
                        help_text="Organisation licence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_services",
                        to="organisation.licence",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="seasonalservice",
            constraint=models.UniqueConstraint(
                fields=("licence", "registration_code"), name="unique_service"
            ),
        ),
    ]
