# Generated by Django 4.2.9 on 2024-06-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naptan", "0007_alter_flexiblezone_naptan_stoppoint_and_more"),
        ("organisation", "0061_faresstuckrevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="admin_areas",
            field=models.ManyToManyField(
                related_name="organisation_atco", to="naptan.adminarea"
            ),
        ),
    ]
