# Generated by Django 4.2.9 on 2024-07-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naptan", "0007_alter_flexiblezone_naptan_stoppoint_and_more"),
        ("organisation", "0062_organisation_admin_areas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="admin_areas",
            field=models.ManyToManyField(
                blank=True, related_name="organisation_atco", to="naptan.adminarea"
            ),
        ),
    ]
