# Generated by Django 4.2.14 on 2024-09-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0064_alter_dataset_avl_feed_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecodeexemption",
            name="registration_code",
            field=models.CharField(
                help_text="The part of the service code after the licence prefix",
                max_length=50,
            ),
        ),
    ]
