# Generated by Django 4.2.14 on 2024-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0066_alter_servicecodeexemption_registration_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetrevision",
            name="modified_file_hash",
            field=models.CharField(
                default="", max_length=40, verbose_name="Hash of modified file"
            ),
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="original_file_hash",
            field=models.CharField(
                default="", max_length=40, verbose_name="Hash of original upload file"
            ),
        ),
    ]
