# Generated by Django 4.2.14 on 2024-11-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0066_alter_servicecodeexemption_registration_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="txcfileattributes",
            name="service_mode",
            field=models.CharField(default="bus", max_length=20, verbose_name="Mode"),
        ),
    ]
