# Generated by Django 4.2.14 on 2025-01-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0033_alter_servicepatternstop_id"),
        ("organisation", "0068_txcfileattributes_service_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumerfeedback",
            name="is_suppressed",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Contains whether the observation result is suppressed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consumerfeedback",
            name="revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_revision",
                to="organisation.datasetrevision",
            ),
        ),
        migrations.AddField(
            model_name="consumerfeedback",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_service",
                to="transmodel.service",
            ),
        ),
        migrations.AddField(
            model_name="consumerfeedback",
            name="service_pattern_stop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_service_pattern_stop",
                to="transmodel.servicepatternstop",
            ),
        ),
        migrations.AddField(
            model_name="consumerfeedback",
            name="vehicle_journey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_vehicle_journey",
                to="transmodel.vehiclejourney",
            ),
        ),
    ]
