# Generated by Django 4.2.14 on 2025-02-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0070_consumerfeedback_service_pattern_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="avl_sra",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="fares_sra",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="overall_sra",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="timetable_sra",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="total_inscope",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
