# Generated by Django 4.2.14 on 2025-04-04 08:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0071_organisation_avl_sra_organisation_fares_sra_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Registration:Service Number",
                    ),
                ),
                (
                    "service_number",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="Registration:Service Number",
                    ),
                ),
                (
                    "scope_status",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Scope Status"
                    ),
                ),
                (
                    "seasonal_status",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Seasonal Status"
                    ),
                ),
                (
                    "organisation_name",
                    models.CharField(
                        max_length=512,
                        null=True,
                        verbose_name="Published Organisation Name",
                    ),
                ),
                (
                    "overall_requires_attention",
                    models.CharField(
                        max_length=64,
                        null=True,
                        verbose_name="Overall Require Attention",
                    ),
                ),
                (
                    "requires_attention",
                    models.CharField(
                        max_length=64,
                        null=True,
                        verbose_name="Timetable Require Attention",
                    ),
                ),
                (
                    "published_status",
                    models.CharField(
                        max_length=64,
                        null=True,
                        verbose_name="Timetables Published Status",
                    ),
                ),
                (
                    "staleness_status",
                    models.CharField(
                        max_length=64,
                        null=True,
                        verbose_name="Timetables Timeliness Status",
                    ),
                ),
                (
                    "critical_dq_issues",
                    models.CharField(
                        max_length=64,
                        null=True,
                        verbose_name="Timetables critical DQ issues",
                    ),
                ),
                (
                    "dataset_id",
                    models.IntegerField(
                        null=True, verbose_name="Timetables Data set ID"
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        max_length=1024, null=True, verbose_name="TXC:Filename"
                    ),
                ),
                (
                    "national_operator_code",
                    models.CharField(
                        max_length=64, null=True, verbose_name="TXC:Filename"
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TXC:Last Modified Date"
                    ),
                ),
                (
                    "effective_stale_date_from_last_modified",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date when timetable data is over 1 year old",
                    ),
                ),
                (
                    "operating_period_end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="TXC:Operating Period End Date",
                    ),
                ),
                (
                    "effective_stale_date_from_otc_effective",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date Registration variation needs to be published",
                    ),
                ),
                (
                    "date_42_day_look_ahead",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date for complete 42 day look ahead",
                    ),
                ),
                (
                    "effective_seasonal_start",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date seasonal service should be published",
                    ),
                ),
                (
                    "seasonal_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Seasonal Start Date"
                    ),
                ),
                (
                    "seasonal_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Seasonal End Date"
                    ),
                ),
                (
                    "avl_requires_attention",
                    models.CharField(
                        max_length=64, null=True, verbose_name="AVL requires attention"
                    ),
                ),
                (
                    "avl_published_status",
                    models.CharField(
                        max_length=64, null=True, verbose_name="AVL Published Status"
                    ),
                ),
                (
                    "error_in_avl_to_timetable_matching",
                    models.CharField(
                        max_length=64,
                        null=True,
                        verbose_name="Error in AVL to Timetable Matching",
                    ),
                ),
                (
                    "fares_requires_attention",
                    models.CharField(
                        max_length=64,
                        null=True,
                        verbose_name="Fares requires attention",
                    ),
                ),
                (
                    "fares_published_status",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Fares Published Status"
                    ),
                ),
                (
                    "fares_timeliness_status",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Fares Timeliness Status"
                    ),
                ),
                (
                    "fares_compliance_status",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Fares Compliance Status"
                    ),
                ),
                (
                    "fares_dataset_id",
                    models.IntegerField(null=True, verbose_name="Fares Data set ID"),
                ),
                (
                    "fares_filename",
                    models.CharField(
                        max_length=1024, null=True, verbose_name="NETEX:Filename"
                    ),
                ),
                (
                    "fares_last_modified_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="NETEX:Last Modified Date"
                    ),
                ),
                (
                    "fares_effective_stale_date_from_last_modified",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date when fares data is over 1 year old",
                    ),
                ),
                (
                    "fares_operating_period_end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="NETEX:Operating Period End Date",
                    ),
                ),
                (
                    "operator_name",
                    models.CharField(
                        max_length=512,
                        null=True,
                        verbose_name="Registration:Operator Name",
                    ),
                ),
                (
                    "otc_licence_number",
                    models.CharField(
                        max_length=64,
                        null=True,
                        verbose_name="Registration:Licence Number",
                    ),
                ),
                (
                    "service_type_description",
                    models.CharField(
                        max_length=64,
                        null=True,
                        verbose_name="Registration:Service Type Description",
                    ),
                ),
                (
                    "variation_number",
                    models.CharField(
                        max_length=64,
                        null=True,
                        verbose_name="Registration:Variation Number",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Registration:Expiry Date"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Registration:Effective Date",
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Registration:Received Date"
                    ),
                ),
                (
                    "traveline_region",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Traveline Region",
                    ),
                ),
                (
                    "local_authority_ui_lta",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Local Transport Authority",
                    ),
                ),
                (
                    "publish_organisation_id",
                    models.IntegerField(
                        db_index=True, null=True, verbose_name="Publish Organisation ID"
                    ),
                ),
                (
                    "licence_organisation_id",
                    models.IntegerField(
                        db_index=True, null=True, verbose_name="Licence Organisation ID"
                    ),
                ),
                (
                    "licence_organisation_name",
                    models.CharField(
                        max_length=512,
                        null=True,
                        verbose_name="Licence Organisation Name",
                    ),
                ),
                (
                    "local_authorities_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            db_index=True,
                            max_length=100,
                            verbose_name="Local Transport Authority IDs",
                        ),
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "ordering": ("registration_number",),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
