# Generated by Django 4.2.14 on 2025-03-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0071_organisation_avl_sra_organisation_fares_sra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="is_franchise",
            field=models.BooleanField(
                default=False,
                help_text="Whether the organisation is a franchise or not",
            ),
        ),
    ]
