# Generated by Django 4.2.14 on 2025-04-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0072_compliancereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="is_franchise",
            field=models.BooleanField(
                default=False,
                help_text="Whether the organisation is a franchise or not",
            ),
        ),
    ]
