# Generated by Django 4.2.14 on 2025-06-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0073_organisation_is_franchise"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetrevision",
            name="modified_before_reprocessing",
            field=models.DateTimeField(
                help_text="The modified field value before reprocessing",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="status_before_reprocessing",
            field=models.CharField(
                default="",
                max_length=20,
                verbose_name="The Status field value before reprocessing",
            ),
        ),
    ]
