# Generated by Django 4.2.14 on 2025-06-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0074_datasetrevision_modified_before_reprocessing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancereport",
            name="derived_termination_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="TXC:Derived Termination Date"
            ),
        ),
        migrations.AddField(
            model_name="compliancereport",
            name="revision_number",
            field=models.CharField(
                max_length=64, null=True, verbose_name="TXC:Revision Number"
            ),
        ),
    ]
