# Generated by Django 4.2.14 on 2025-06-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0075_alter_datasetrevision_upload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancereport",
            name="derived_termination_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="TXC:Derived Termination Date"
            ),
        ),
        migrations.AddField(
            model_name="compliancereport",
            name="revision_number",
            field=models.CharField(
                max_length=64, null=True, verbose_name="TXC:Revision Number"
            ),
        ),
    ]
