# Generated by Django 4.2.14 on 2025-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0076_compliancereport_derived_termination_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancereport",
            name="operating_period_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="TXC:Operating Period Start Date"
            ),
        ),
    ]
