# Generated by Django 4.2.23 on 2025-09-02 10:38

from django.db import migrations, models
import transit_odp.organisation.constants


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0077_compliancereport_operating_period_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetrevision",
            name="deletion_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="deletion_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="deletion_status",
            field=models.CharField(
                choices=[
                    (
                        transit_odp.organisation.constants.DeletionStatus["PENDING"],
                        "Pending",
                    ),
                    (
                        transit_odp.organisation.constants.DeletionStatus["DELETING"],
                        "Deleting",
                    ),
                    (
                        transit_odp.organisation.constants.DeletionStatus["DELETED"],
                        "Deleted",
                    ),
                    (
                        transit_odp.organisation.constants.DeletionStatus["FAILED"],
                        "Failed",
                    ),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="datasetrevision",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
