# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from cavl_server import util
from cavl_server.models.base_model_ import Model


class Feed(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        id: int = None,
        publisher_id: int = None,
        url: str = None,
        username: str = None,
        password: str = None,
        status: str = "DEPLOYING",
        created: datetime = None,
        modified: datetime = None,
    ):  # noqa: E501
        """Feed - a model defined in Swagger

        :param id: The id of this Feed.  # noqa: E501
        :type id: int
        :param publisher_id: The publisher_id of this Feed.  # noqa: E501
        :type publisher_id: int
        :param url: The url of this Feed.  # noqa: E501
        :type url: str
        :param username: The username of this Feed.  # noqa: E501
        :type username: str
        :param password: The password of this Feed.  # noqa: E501
        :type password: str
        :param status: The status of this Feed.  # noqa: E501
        :type status: str
        :param created: The created of this Feed.  # noqa: E501
        :type created: datetime
        :param modified: The modified of this Feed.  # noqa: E501
        :type modified: datetime
        """
        self.swagger_types = {
            "id": int,
            "publisher_id": int,
            "url": str,
            "username": str,
            "password": str,
            "status": str,
            "created": datetime,
            "modified": datetime,
        }

        self.attribute_map = {
            "id": "id",
            "publisher_id": "publisherId",
            "url": "url",
            "username": "username",
            "password": "password",
            "status": "status",
            "created": "created",
            "modified": "modified",
        }
        self._id = id
        self._publisher_id = publisher_id
        self._url = url
        self._username = username
        self._password = password
        self._status = status
        self._created = created
        self._modified = modified

    @classmethod
    def from_dict(cls, dikt) -> "Feed":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Feed of this Feed.  # noqa: E501
        :rtype: Feed
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Feed.


        :return: The id of this Feed.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Feed.


        :param id: The id of this Feed.
        :type id: int
        """

        self._id = id

    @property
    def publisher_id(self) -> int:
        """Gets the publisher_id of this Feed.


        :return: The publisher_id of this Feed.
        :rtype: int
        """
        return self._publisher_id

    @publisher_id.setter
    def publisher_id(self, publisher_id: int):
        """Sets the publisher_id of this Feed.


        :param publisher_id: The publisher_id of this Feed.
        :type publisher_id: int
        """

        self._publisher_id = publisher_id

    @property
    def url(self) -> str:
        """Gets the url of this Feed.


        :return: The url of this Feed.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Feed.


        :param url: The url of this Feed.
        :type url: str
        """

        self._url = url

    @property
    def username(self) -> str:
        """Gets the username of this Feed.


        :return: The username of this Feed.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Feed.


        :param username: The username of this Feed.
        :type username: str
        """

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this Feed.


        :return: The password of this Feed.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this Feed.


        :param password: The password of this Feed.
        :type password: str
        """

        self._password = password

    @property
    def status(self) -> str:
        """Gets the status of this Feed.

        Feed Consumer Status  # noqa: E501

        :return: The status of this Feed.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Feed.

        Feed Consumer Status  # noqa: E501

        :param status: The status of this Feed.
        :type status: str
        """
        allowed_values = [
            "DEPLOYING",
            "SYSTEM_ERROR",
            "FEED_UP",
            "FEED_DOWN",
        ]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}".format(
                    status, allowed_values
                )
            )

        self._status = status

    @property
    def created(self) -> datetime:
        """Gets the created of this Feed.


        :return: The created of this Feed.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created: datetime):
        """Sets the created of this Feed.


        :param created: The created of this Feed.
        :type created: datetime
        """

        self._created = created

    @property
    def modified(self) -> datetime:
        """Gets the modified of this Feed.


        :return: The modified of this Feed.
        :rtype: datetime
        """
        return self._modified

    @modified.setter
    def modified(self, modified: datetime):
        """Sets the modified of this Feed.


        :param modified: The modified of this Feed.
        :type modified: datetime
        """

        self._modified = modified
