# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from cavl_server import util
from cavl_server.models.base_model_ import Model


class InlineResponse201(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int = None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger

        :param id: The id of this InlineResponse201.  # noqa: E501
        :type id: int
        """
        self.swagger_types = {"id": int}

        self.attribute_map = {"id": "id"}
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> "InlineResponse201":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse201.

        ID of the created feed.  # noqa: E501

        :return: The id of this InlineResponse201.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse201.

        ID of the created feed.  # noqa: E501

        :param id: The id of this InlineResponse201.
        :type id: int
        """

        self._id = id
