# Generated by Django 3.1.13 on 2021-12-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("number", models.CharField(max_length=9, unique=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("valid", "Valid"),
                            ("curtailed", "Curtailed"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discs_in_possession", models.IntegerField(null=True)),
                ("authdiscs", models.IntegerField(null=True)),
                ("operator_id", models.IntegerField(unique=True)),
                ("operator_name", models.CharField(max_length=100)),
                ("trading_name", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(blank=True, max_length=20)),
                ("variation_number", models.IntegerField()),
                ("service_number", models.CharField(max_length=50)),
                (
                    "current_traffic_area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("B", "North East"),
                            ("C", "North West"),
                            ("D", "West Midlands"),
                            ("F", "East of England"),
                            ("G", "Wales"),
                            ("H", "West of England"),
                            ("K", "London and South East"),
                            ("M", "Scotland"),
                        ],
                        max_length=1,
                    ),
                ),
                ("start_point", models.CharField(blank=True, max_length=100)),
                ("finish_point", models.CharField(blank=True, max_length=100)),
                ("via", models.TextField(blank=True)),
                ("effective_date", models.DateField(null=True)),
                ("received_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                ("service_type_other_details", models.TextField(blank=True)),
                ("registration_code", models.IntegerField(null=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("standard national", "Standard national"),
                            ("standard international", "Standard international"),
                            ("restricted", "Restricted"),
                            ("special restricted", "Special restricted"),
                        ],
                        max_length=25,
                    ),
                ),
                ("registration_status", models.CharField(blank=True, max_length=20)),
                ("public_text", models.TextField(blank=True)),
                (
                    "service_type_description",
                    models.CharField(blank=True, max_length=50),
                ),
                ("short_notice", models.BooleanField(null=True)),
                (
                    "subsidies_description",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No"), ("in part", "In Part")],
                        max_length=7,
                    ),
                ),
                ("subsidies_details", models.CharField(blank=True, max_length=100)),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="otc.licence",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="otc.operator",
                    ),
                ),
            ],
        ),
    ]
