# Generated by Django 3.1.14 on 2021-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operator",
            name="trading_name",
        ),
        migrations.AlterField(
            model_name="service",
            name="registration_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
