# Generated by Django 3.1.14 on 2022-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otc", "0002_change_service_search_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="subsidies_description",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No"), ("In Part", "In Part")],
                max_length=7,
            ),
        ),
    ]
