# Generated by Django 3.2.16 on 2022-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otc", "0003_fixed_subsidies_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="last_modified",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="licence",
            name="expiry_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="licence",
            name="granted_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="licence",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("valid", "Valid"),
                    ("curtailed", "Curtailed"),
                    ("suspended", "Suspended"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="operator",
            name="operator_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
