# Generated by Django 3.2.16 on 2022-11-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otc", "0004_add_last_modified_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="finish_point",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="start_point",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="subsidies_details",
            field=models.TextField(blank=True),
        ),
    ]
