# Generated by Django 3.2.16 on 2023-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otc", "0006_auto_20230331_1028"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalAuthority",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True)),
                (
                    "registration_numbers",
                    models.ManyToManyField(
                        related_name="registration", to="otc.Service"
                    ),
                ),
            ],
        ),
    ]
