# Generated by Django 3.2.16 on 2023-06-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0007_localauthority'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuthorityMappingAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otc_lta_name', models.CharField(max_length=255, unique=True)),
                ('ui_lta_name', models.CharField(max_length=255)),
                ('atco_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
