# Generated by Django 3.2.16 on 2023-08-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otc", "0009_inactiveservice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InactiveService",
        ),
    ]
