# Generated by Django 3.2.20 on 2023-12-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0011_auto_20231208_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localauthority',
            name='atco_code',
        ),
    ]
