# Generated by Django 4.2.9 on 2024-02-19 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("otc", "0012_remove_localauthority_atco_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="api_type",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="atco_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="licence",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="otc.licence",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="operator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="otc.operator",
            ),
        ),
    ]
