# Generated by Django 4.2.9 on 2024-04-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otc", "0013_service_api_type_service_atco_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="registration_number",
            field=models.CharField(max_length=25),
        ),
    ]
