# Generated by Django 4.2.14 on 2025-03-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otc", "0014_alter_service_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="uilta",
            name="avl_sra",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="uilta",
            name="fares_sra",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="uilta",
            name="overall_sra",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="uilta",
            name="timetable_sra",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="uilta",
            name="total_inscope",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
