# Generated by Django 4.2.23 on 2026-08-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otc", "0015_uilta_avl_sra_uilta_fares_sra_uilta_overall_sra_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inactiveservice",
            name="registration_number",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
