# Generated by Django 3.2.16 on 2023-08-12 18:03

from django.db import migrations, models
import django_extensions.db.fields
import transit_odp.common.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisruptionsDataArchive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "last_updated",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="last_updated"
                    ),
                ),
                (
                    "data",
                    transit_odp.common.fields.CallableStorageFileField(
                        help_text="A zip file containing an up to date SIRI-SX XML.",
                        upload_to="",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "-created",
            },
        ),
    ]
