# Generated by Django 4.2.23 on 2025-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disruptions", "0002_alter_disruptionsdataarchive_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="disruptionsdataarchive",
            name="data_format",
            field=models.CharField(
                choices=[("SX", "Siri SX"), ("RT", "GTFS RT")],
                default="SX",
                max_length=2,
            ),
        ),
    ]
