# coding: utf-8

"""
    CAVL Config API

    Used to configure feed consumers in the CAVL Service  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: greg.brown@itoworld.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import find_packages, setup  # noqa: H301

NAME = "cavl-client"
VERSION = "0.1.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="CAVL Config API",
    author_email="greg.brown@itoworld.com",
    url="",
    keywords=["Swagger", "CAVL Config API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Used to configure feed consumers in the CAVL Service  # noqa: E501
    """,
)
