# coding: utf-8

# flake8: noqa
"""
    CAVL Config API

    Used to configure feed consumers in the CAVL Service  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: greg.brown@itoworld.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from cavl_client.models.body import Body
from cavl_client.models.feed import Feed
from cavl_client.models.inline_response201 import InlineResponse201
from cavl_client.models.validation_task_result import ValidationTaskResult
