name: update_task_definition

# Were we can define the inputs that our action will accept
inputs:
  service: 
    required: true
  container: 
    required: true
  environment:
    required: true
  image_id:
    required: true

runs:
  using: "composite"
  steps:

  # aws-ecs/deploy-service-update 
  - name: Download task definition
    shell: bash
    run: |
      aws ecs describe-task-definition --task-definition bodds_${{ inputs.service }}_${{ inputs.environment }} --query taskDefinition > ${{ github.workspace }}/task-definition.json

  - name: Fill in the new image ID in the Amazon ECS task definition
    id: task-def
    uses: aws-actions/amazon-ecs-render-task-definition@v1
    with:
      task-definition: task-definition.json
      container-name: ${{ inputs.container }}
      image: ${{ inputs.image_id }}

  - name: Deploy Amazon ECS task definition
    uses: aws-actions/amazon-ecs-deploy-task-definition@v1
    with:
      task-definition: ${{ steps.task-def.outputs.task-definition }}
      service: ${{ inputs.service }}
      cluster: bodds-${{ inputs.environment }}
      wait-for-service-stability: true