name: update_task_definition

description: Updates a task definition with a new image and deploys it using AWS maintained github actions

inputs:
  service:
    description: The name of the service
    required: true
  container:
    description: The name of the container inside the task definition needing patched
    required: true
  environment:
    description: The environment being targeted
    required: true
  image_id:
    description: The updated image
    required: true

runs:
  using: "composite"
  steps:
    - name: Render ECS task definition
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@6853cfae8c3a7d978fbf68b5a55453395541dfbb # 1.8.5
      with:
        task-definition-family: bodds_${{ inputs.service }}_${{ inputs.environment }}
        container-name: ${{ inputs.container }}
        image: ${{ inputs.image_id }}

    - name: Deploy ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@a310a830f5c14e583e35d84e4e1ec7dd177c3c9c # 2.6.2
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        service: ${{ inputs.service }}
        cluster: bodds-${{ inputs.environment }}
        wait-for-service-stability: true

