# Generated by Django 3.1.13 on 2021-09-30 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0004_set_site_subdomains"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={
                "ordering": ["domain"],
                "verbose_name": "site",
                "verbose_name_plural": "sites",
            },
        ),
    ]
