from collections import OrderedDict

# Key - OTC LTA name - Col B, Value - Col A
LTAS_DICT = OrderedDict(
    {
        "Bedford County Council": "Bedford Borough Council",
        "Blackburn with Darwen Borough Council": "Blackburn with Darwen Borough Council",
        "Blackpool Borough Council": "Blackpool Council",
        "Bournemouth Borough Council, Poole Borough Council": "Bournemouth, Christchurch and Poole Council",
        "Bracknell Forest Borough Council": "Bracknell Forest Council",
        "Brighton & Hove City Council": "Brighton and Hove City Council",
        "Buckinghamshire County Council": "Buckinghamshire County Council",
        "Cambridgeshire County Council, Peterborough City Council": "Cambridgeshire and Peterborough Combined Authority",
        "Bedfordshire County Council": "Central Bedfordshire Council",
        "Cheshire East Council": "Cheshire East Council",
        "Cheshire West and Chester Council": "Cheshire West and Chester Council",
        "York City Council": "City of York Council",
        "CornwallAndScillies": "Cornwall Council (including Isles of Scilly)",
        "Cumbria County Council": "Cumbria County Council",
        "Derby City Council": "Derby City Council",
        "Derbyshire County Council": "Derbyshire County Council",
        "Devon": "Devon County Council",
        "Dorset County Council": "Dorset Council",
        "East Riding of Yorkshire Council": "East Riding of Yorkshire Council",
        "East Sussex County Council": "East Sussex County Council",
        "Essex County Council": "Essex County Council",
        "Gloucestershire County Council": "Gloucestershire County Council",
        "Transport for Greater Manchester (TFGM)": "Greater Manchester Combined Authority",
        "Hampshire Council": "Hampshire County Council",
        "Herefordshire Council": "Herefordshire Council",
        "Hertfordshire County Council": "Hertfordshire County Council",
        "Isle of Wight Council": "Isle of Wight Council",
        "Kent County Council": "Kent County Council",
        "Lancashire County Council": "Lancashire County Council",
        "Leicester City Council": "Leicester City Council",
        "Leicestershire County Council": "Leicestershire County Council",
        "Lincolnshire County Council": "Lincolnshire County Council",
        "Luton Borough Council": "Luton Borough Council",
        "Medway Council": "Medway Council",
        "Milton Keynes Council": "Milton Keynes Council",
        "Norfolk County Council": "Norfolk County Council",
        "North East Lincolnshire Council": "North East Lincolnshire Council",
        "North Lincolnshire Council": "North Lincolnshire Council",
        "Nexus (Tyne & Wear)": "North of Tyne Combined Authority",
        "North Somerset Council": "North Somerset Council",
        "North Yorkshire County Council": "North Yorkshire County Council",
        "Nottingham City Council": "Nottingham City Council",
        "Nottinghamshire County Council": "Nottinghamshire County Council",
        "Oxfordshire County Council": "Oxfordshire County Council",
        "Plymouth City Council": "Plymouth City Council",
        "Portsmouth City Council": "Portsmouth City Council",
        "Reading Borough Council": "Reading Borough Council",
        "Windsor & Maidenhead Borough Council": "Royal Borough of Windsor and Maidenhead",
        "Rutland County Council": "Rutland County Council",
        "Shropshire County Council": "Shropshire Council",
        "Slough Borough Council": "Slough Borough Council",
        "Somerset County Council": "Somerset County Council",
        "Southampton City Council": "Southampton City Council",
        "Southend-on-Sea Borough Council": "Southend-on-Sea Borough Council",
        "Staffordshire County Council": "Staffordshire County Council",
        "City of Stoke-on-Trent Council": "Stoke-on-Trent City Council",
        "Suffolk County Council": "Suffolk County Council",
        "Surrey County Council": "Surrey County Council",
        "Swindon Borough Council": "Swindon Borough Council",
        "Telford & Wrekin Council": "Telford & Wrekin Council",
        "Thurrock Council": "Thurrock Council",
        "Torbay Borough Council": "Torbay Council",
        "Warrington Borough Council": "Warrington Borough Council",
        "Warwickshire County Council": "Warwickshire County Council",
        "West Berkshire District Council": "West Berkshire Council",
        "West Midlands Combined Authority (WMCA)": "West Midlands Combined Authority",
        "Northamptonshire County Council": "West Northamptonshire Council",
        "West Sussex County Council": "West Sussex County Council",
        "West Yorkshire pte": "West Yorkshire Combined Authority",
        "Wiltshire County Council": "Wiltshire Council",
        "Wokingham District Council": "Wokingham Borough Council",
        "Worcestershire County Council": "Worcestershire County Council",
    }
)

LTA_LIST = [
    "Bedford County Council",
    "Blackburn with Darwen Borough Council",
    "Blackpool Borough Council",
    "Bournemouth Borough Council, Poole Borough Council",
    "Bracknell Forest Borough Council",
    "Brighton & Hove City Council",
    "Buckinghamshire County Council",
    "Cambridgeshire County Council, Peterborough City Council",
    "Bedfordshire County Council",
    "Cheshire East Council",
    "Cheshire West and Chester Council",
    "York City Council",
    "CornwallAndScillies",
    "Cumbria County Council",
    "Derby City Council",
    "Derbyshire County Council",
    "Devon",
    "Dorset County Council",
    "East Riding of Yorkshire Council",
    "East Sussex County Council",
    "Essex County Council",
    "Gloucestershire County Council",
    "Transport for Greater Manchester (TFGM)",
    "Hampshire Council",
    "Herefordshire Council",
    "Hertfordshire County Council",
    "Isle of Wight Council",
    "Kent County Council",
    "Lancashire County Council",
    "Leicester City Council",
    "Leicestershire County Council",
    "Lincolnshire County Council",
    "Luton Borough Council",
    "Medway Council",
    "Milton Keynes Council",
    "Norfolk County Council",
    "North East Lincolnshire Council",
    "North Lincolnshire Council",
    "Northamptonshire County Council",
    "Nexus (Tyne & Wear)",
    "North Somerset Council",
    "North Yorkshire County Council",
    "Nottingham City Council",
    "Nottinghamshire County Council",
    "Oxfordshire County Council",
    "Plymouth City Council",
    "Portsmouth City Council",
    "Reading Borough Council",
    "Windsor & Maidenhead Borough Council",
    "Rutland County Council",
    "Shropshire County Council",
    "Slough Borough Council",
    "Somerset County Council",
    "Southampton City Council",
    "Southend-on-Sea Borough Council",
    "Staffordshire County Council",
    "City of Stoke-on-Trent Council",
    "Suffolk County Council",
    "Surrey County Council",
    "Swindon Borough Council",
    "Telford & Wrekin Council",
    "Thurrock Council",
    "Torbay Borough Council",
    "Warrington Borough Council",
    "Warwickshire County Council",
    "West Berkshire District Council",
    "West Midlands Combined Authority (WMCA)",
    "West Sussex County Council",
    "West Yorkshire pte",
    "Wiltshire County Council",
    "Wokingham District Council",
    "Worcestershire County Council",
]
