# Generated by Django 3.2.13 on 2022-05-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisation", "0052_add_consumer_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableDataset",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("organisation.dataset",),
        ),
        migrations.CreateModel(
            name="TimetableDatasetRevision",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("organisation.datasetrevision",),
        ),
    ]
