from collections import OrderedDict

from pandas import DataFrame, merge

from transit_odp.common.collections import Column
from transit_odp.fares.models import DataCatalogueMetaData
from transit_odp.organisation.csv import EmptyDataFrame
from transit_odp.organisation.models import (
    Dataset,
    DatasetMetadata,
    DatasetRevision,
    TXCFileAttributes,
)

OVERALL_COLUMN_MAP = OrderedDict(
    {
        "organisation_name": Column(
            "Operator", "The name of the operator/publisher providing data on BODS."
        ),
        "organisation_id": Column(
            "Operator ID",
            "The internal BODS generated ID of the operator/publisher providing"
            " data on BODS.",
        ),
        "profile_nocs": Column(
            "Profile NOCs",
            (
                "The National Operator Codes for the particular publisher as extracted "
                "from their BODS profile."
            ),
        ),
        "dataset_type_pretty": Column("Data Type", "The type of data being published."),
        "status": Column("Status", "The publication status of the data set/feed."),
        "last_updated": Column(
            "Last Updated", "The date that the data set/feed was last updated on BODS."
        ),
        "upload_filename": Column(
            "File Name",
            "The exact name of the file provided to BODS. This is usually generated by "
            "the publisher or their supplier",
        ),
        "filename": Column(
            "XML File Name",
            "The value of the FileName attribute in the TransXChange file.",
        ),
        "name": Column(
            "Data Set/Feed Name",
            "The internal BODS generated data set name given for a particular"
            " data set.",
        ),
        "id": Column(
            "Data ID",
            "The internal BODS generated ID of the data set / feed provided to BODS.",
        ),
        "mode": Column(
            "Mode",
            "The mode of transport as extracted from the TransXChange "
            "file they provided.",
        ),
        "national_operator_code": Column(
            "National Operator Code",
            "The National Operator Codes for the particular publisher as extracted"
            " from the TransXChange file they provided.",
        ),
        "service_code": Column(
            "Service Code",
            "The ServiceCode for the particular publisher as extracted from "
            "the TransXChange file they provided.",
        ),
        "string_lines": Column(
            "Line Name",
            "The linename for the particular publisher as extracted from "
            "the TransXChange file they provided.",
        ),
    }
)

DATASET_FIELDS = (
    "organisation_name",
    "organisation_id",
    "profile_nocs",
    "dataset_type_pretty",
    "status",
    "last_updated",
    "upload_filename",
    "id",
    "name",
)

TXC_FILE_ATTRIBUTE_FIELDS = (
    "dataset_id",
    "filename",
    "national_operator_code",
    "service_code",
    "string_lines",
)

DATACATALOGUE_ATTRIBUTE_FIELDS = (
    "fares_metadata_id",
    "xml_file_name",
    "national_operator_code",
    "line_name",
)


def get_fares_data_list(
    filtered_fares_data_dict, filtered_revision_ids_dict, filtered_dataset_ids_dict
):
    """
    Returns list of fares information (xml file name, NOCs and line name)
    when dataset_id in DatasetRevision table match
    fares_metadata_id in DataCatalogueMetaData table.
    """
    for fares_data_dict in filtered_fares_data_dict:
        for revision_id_dict in filtered_revision_ids_dict:
            if fares_data_dict.get("fares_metadata_id") == revision_id_dict.get("id"):
                fares_data_dict["revision_id"] = revision_id_dict["revision_id"]

        for dataset_id_dict in filtered_dataset_ids_dict:
            if fares_data_dict.get("revision_id") == dataset_id_dict.get("id"):
                fares_data_dict["dataset_id"] = dataset_id_dict["dataset_id"]

    return list(filtered_fares_data_dict)


def transform_lists(data_list):
    """
    Transform lists to seperate multiple values in a list
    with a semi-colon
    """
    transformed_string = "".join([str(data) + "; " for data in data_list]).removesuffix(
        "; "
    )
    return transformed_string


def _get_overall_catalogue_dataframe() -> DataFrame:
    dataset_df = DataFrame.from_records(
        Dataset.objects.get_overall_data_catalogue_annotations().values(*DATASET_FIELDS)
    )
    txc_file_attributes_df = DataFrame.from_records(
        TXCFileAttributes.objects.get_overall_data_catalogue().values(
            *TXC_FILE_ATTRIBUTE_FIELDS
        )
    )
    datacatalogue_metadata_qs = (
        DataCatalogueMetaData.objects.get_fares_overall_catalogue().values(
            *DATACATALOGUE_ATTRIBUTE_FIELDS
        )
    )
    revision_id_qs = DatasetMetadata.objects.revision_id_qs().values(
        "id", "revision_id"
    )
    dataset_id_qs = DatasetRevision.objects.dataset_id_qs().values("id", "dataset_id")

    if dataset_df.empty or txc_file_attributes_df.empty:
        raise EmptyDataFrame()

    merged = merge(
        dataset_df,
        txc_file_attributes_df,
        left_on="id",
        right_on="dataset_id",
        how="outer",
    )
    merged["mode"] = "Bus"
    merged = merged.sort_values("id")
    rename_map = {
        old_name: column_tuple.field_name
        for old_name, column_tuple in OVERALL_COLUMN_MAP.items()
    }
    merged = merged[OVERALL_COLUMN_MAP.keys()].rename(columns=rename_map)

    fares_data_dict = get_fares_data_list(
        datacatalogue_metadata_qs,
        revision_id_qs,
        dataset_id_qs,
    )

    for row in merged.itertuples():
        for data_dict in fares_data_dict:
            if data_dict.get("dataset_id") == getattr(row, "_10"):
                xml_file_name = data_dict.get("xml_file_name")
                national_operator_code = transform_lists(
                    data_dict.get("national_operator_code")
                )
                line_name = transform_lists(data_dict.get("line_name"))

                merged.loc[row.Index, ["XML File Name"]] = xml_file_name
                merged.loc[
                    row.Index, ["National Operator Code"]
                ] = national_operator_code
                merged.loc[row.Index, ["Line Name"]] = line_name

    return merged


def get_overall_data_catalogue_csv() -> str:
    return _get_overall_catalogue_dataframe().to_csv(index=False)
