# Generated by Django 2.2.6 on 2019-11-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0003_vehiclejourney"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timingpatternstop",
            name="pickup_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="timingpatternstop",
            name="setdown_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="timingpatternstop",
            name="timing_point",
            field=models.BooleanField(default=False),
        ),
    ]
