# Generated by Django 3.2.20 on 2023-11-15 10:33

from django.db import migrations, models


def set_default_for_existing_rows(apps, schema_editor):
    YourModel = apps.get_model("transmodel", "Service")
    YourModel.objects.filter(service_type__isnull=True).update(service_type="standard")


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0005_add_booking_arrangements"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.CharField(default="standard", max_length=255),
        ),
        migrations.RunPython(set_default_for_existing_rows),
    ]
