# Generated by Django 4.1.13 on 2024-01-26 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0006_flexibleserviceoperationperiod_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiclejourney",
            name="timing_pattern",
        ),
        migrations.DeleteModel(
            name="TimingPattern",
        ),
    ]
