# Generated by Django 4.2.7 on 2024-01-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0007_remove_vehiclejourney_timing_pattern_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclejourney",
            name="start_time",
            field=models.TimeField(null=True),
        ),
    ]
