# Generated by Django 4.1.13 on 2024-01-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0008_alter_vehiclejourney_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicedorganisations",
            name="vehicle_journeys",
        ),
        migrations.AlterField(
            model_name="servicedorganisationvehiclejourney",
            name="serviced_organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="serviced_organisations",
                to="transmodel.servicedorganisations",
            ),
        ),
        migrations.AlterField(
            model_name="servicedorganisationvehiclejourney",
            name="vehicle_journey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_journeys",
                to="transmodel.vehiclejourney",
            ),
        ),
    ]
