# Generated by Django 4.1.13 on 2024-01-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0009_remove_servicedorganisations_vehicle_journeys_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedorganisations",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
