# Generated by Django 4.1.13 on 2024-02-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0010_alter_servicedorganisations_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicedorganisations",
            name="organisation_code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="servicedorganisations",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
