# Generated by Django 4.2.9 on 2024-02-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0011_servicedorganisations_organisation_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingarrangements",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
    ]
