# Generated by Django 4.2.9 on 2024-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0011_servicedorganisations_organisation_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flexibleserviceoperationperiod",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="flexibleserviceoperationperiod",
            name="start_date",
        ),
        migrations.AddField(
            model_name="flexibleserviceoperationperiod",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flexibleserviceoperationperiod",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
