# Generated by Django 4.1.13 on 2024-02-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0013_bankholidays"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclejourney",
            name="departure_day_shift",
            field=models.BooleanField(default=False),
        ),
    ]
