# Generated by Django 4.1.13 on 2024-02-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0014_vehiclejourney_departure_day_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepattern",
            name="line_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
