# Generated by Django 4.2.7 on 2024-03-04 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0014_vehiclejourney_departure_day_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclejourney",
            name="service_pattern",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_pattern_vehicle_journey",
                to="transmodel.servicepattern",
            ),
        ),
        migrations.AlterField(
            model_name="bookingarrangements",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
