# Generated by Django 4.1.13 on 2024-03-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0014_vehiclejourney_departure_day_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingarrangements",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
