# Generated by Django 4.1.13 on 2024-02-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0015_servicepattern_line_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepattern",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
