# Generated by Django 4.1.13 on 2024-03-06 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0015_servicepattern_line_name"),
        ("transmodel", "0015_vehiclejourney_service_pattern_and_more"),
    ]

    operations = []
