# Generated by Django 4.1.13 on 2024-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0015_servicepattern_line_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingarrangements",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servicepattern",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
