# Generated by Django 4.1.13 on 2024-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0016_merge_20240306_1440"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepattern",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
