# Generated by Django 4.1.13 on 2024-03-07 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0059_alter_dataset_dataset_type"),
        ("transmodel", "0017_alter_servicepattern_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicepattern",
            options={"ordering": ("revision", "service_pattern_id", "line_name")},
        ),
        migrations.AlterUniqueTogether(
            name="servicepattern",
            unique_together={("revision", "service_pattern_id", "line_name")},
        ),
    ]
