# Generated by Django 4.1.13 on 2024-03-11 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0016_alter_servicedorganisations_organisation_code"),
        ("transmodel", "0018_alter_servicepattern_options_and_more"),
    ]

    operations = []
