# Generated by Django 4.2.7 on 2024-03-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0019_merge_20240311_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepatternstop",
            name="vehicle_journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_pattern_stops_vehicle_journey",
                to="transmodel.vehiclejourney",
            ),
        ),
    ]
