# Generated by Django 4.2.9 on 2024-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0020_servicepatternstop_vehicle_journey"),
    ]

    operations = [
        migrations.CreateModel(
            name="StopActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_pickup", models.BooleanField(default=False)),
                ("is_setdown", models.BooleanField(default=False)),
                ("is_driverrequest", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="vehiclejourney",
            name="block_number",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
