# Generated by Django 4.2.9 on 2024-04-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0059_alter_dataset_dataset_type"),
        ("transmodel", "0021_stopactivity_vehiclejourney_block_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="txcfileattributes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_txcfileattributes",
                to="organisation.txcfileattributes",
            ),
        ),
    ]
