# Generated by Django 4.2.9 on 2024-04-24 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0022_service_txcfileattributes_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="servicepattern",
            unique_together=set(),
        ),
    ]
