# Generated by Django 4.1.13 on 2024-04-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0023_alter_servicepattern_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepatternstop",
            name="stop_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_pattern_stops_activity",
                to="transmodel.stopactivity",
            ),
        ),
    ]
