# Generated by Django 4.2.9 on 2024-04-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0024_servicepatternstop_stop_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicedorganisationworkingdays",
            name="serviced_organisation",
        ),
        migrations.AddField(
            model_name="servicedorganisationworkingdays",
            name="serviced_organisation_vehicle_journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="serviced_organisations_vehicle_journey",
                to="transmodel.servicedorganisationvehiclejourney",
            ),
        ),
    ]
