# Generated by Django 4.2.9 on 2024-04-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transmodel",
            "0025_remove_servicedorganisationworkingdays_serviced_organisation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclejourney",
            name="block_number",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
