# Generated by Django 4.2.9 on 2024-07-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transmodel", "0028_alter_servicepatternstop_stop_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepatternstop",
            name="auto_sequence_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
