# Generated by Django 4.2.14 on 2024-09-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0029_servicepatternstop_auto_sequence_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclejourney",
            name="block_number",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
