# Generated by Django 4.2.14 on 2024-10-29 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0030_alter_vehiclejourney_block_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tracks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_atco_code", models.CharField(max_length=255)),
                ("to_atco_code", models.CharField(max_length=255)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("distance", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TracksVehicleJourney",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_number", models.IntegerField(blank=True, null=True)),
                (
                    "tracks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="transmodel.tracks",
                    ),
                ),
                (
                    "vehicle_journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_journey_tracks",
                        to="transmodel.vehiclejourney",
                    ),
                ),
            ],
        ),
    ]
