# Generated by Django 4.2.14 on 2024-12-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0032_alter_tracksvehiclejourney_sequence_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepatternstop",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
