# Generated by Django 4.2.14 on 2025-05-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0035_alter_service_service_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonoperatingdatesexceptions",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
