# Generated by Django 4.2.14 on 2025-05-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0036_alter_nonoperatingdatesexceptions_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracksvehiclejourney",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
