# Generated by Django 4.2.14 on 2025-06-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0037_alter_tracksvehiclejourney_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePatternTracks",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sequence_number", models.IntegerField(blank=True, null=True)),
                (
                    "service_pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_pattern_tracks",
                        to="transmodel.servicepattern",
                    ),
                ),
                (
                    "tracks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmodel_tracks",
                        to="transmodel.tracks",
                    ),
                ),
            ],
        ),
    ]
