# Generated by Django 4.2.14 on 2025-06-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0037_alter_tracksvehiclejourney_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepattern",
            name="tracks",
            field=models.ManyToManyField(
                related_name="service_pattern_tracks", to="transmodel.tracks"
            ),
        ),
    ]
