# Generated by Django 4.2.14 on 2025-06-11 10:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0038_servicepatterntracks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePatternDistance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("distance", models.IntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "service_pattern",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_pattern",
                        to="transmodel.servicepattern",
                    ),
                ),
            ],
        ),
    ]
