# Generated by Django 4.2.14 on 2025-06-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0039_servicepatterndistance"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tracks",
            name="unique_from_to_atco_code",
        ),
    ]
