# Generated by Django 4.2.23 on 2025-09-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transmodel", "0042_tracks_transmodel__from_at_be9861_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepatterndistance",
            name="coord_track_distance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracks",
            name="coord_distance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
