# Generated by Django 2.2.9 on 2020-01-30 16:26
import logging

from django.db import migrations

from transit_odp.organisation.models import Organisation
from transit_odp.users.constants import AccountType

logger = logging.getLogger(__name__)


def populate_key_contact_on_org_with_user(apps, schema_editor):
    logger.info("Adding first org admin to key_contact field on organisation table")
    organisation: Organisation = apps.get_model("organisation", "Organisation")

    for org in organisation.objects.all():
        users = org.user_set.filter(account_type=AccountType.org_admin.value)
        if users:
            org.key_contact = users.earliest("id")
        org.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_invitation_is_key_contact"),
        ("organisation", "0024_organisation_key_contact"),
    ]
    operations = [migrations.RunPython(populate_key_contact_on_org_with_user)]
