# Generated by Django 2.2.13 on 2020-11-25 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_admin", "0002_add_operational_stats"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationalstats",
            options={"verbose_name_plural": "Operational stats"},
        ),
    ]
