# Generated by Django 2.2.17 on 2021-01-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_admin", "0004_added_api_request_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apirequest",
            name="path_info",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="apirequest",
            name="query_string",
            field=models.CharField(max_length=512),
        ),
    ]
