# Generated by Django 2.2.22 on 2021-05-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_admin", "0005_auto_20210113_1804"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apirequest",
            options={"get_latest_by": "modified"},
        ),
    ]
