# Generated by Django 2.2.23 on 2021-07-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_admin", "0007_add_export_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalstats",
            name="vehicle_count",
            field=models.IntegerField(default=0),
        ),
    ]
