# Generated by Django 2.2.23 on 2021-07-29 08:26

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_admin", "0008_added_vehicle_count_column"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalMetricsArchive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("archive", models.FileField(upload_to="")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
