# Generated by Django 3.1.14 on 2022-01-11 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_admin", "0010_add_service_code_counts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OperationalMetricsArchive",
            new_name="DocumentArchive",
        ),
    ]
