# Generated by Django 3.1.14 on 2022-01-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_admin", "0011_rename_op_metrics_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentarchive",
            name="category",
            field=models.CharField(
                choices=[
                    ("operational_metrics", "Operational Metrics"),
                    ("data_catalogue", "Data Catalogue"),
                ],
                default="operational_metrics",
                max_length=50,
            ),
        ),
    ]
