# Generated by Django 3.2.13 on 2022-05-27 14:55

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("site_admin", "0014_allow_null_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apirequest",
            options={},
        ),
        AddIndexConcurrently(
            model_name="apirequest",
            index=models.Index(fields=["created"], name="apirequest_created_idx"),
        ),
        AddIndexConcurrently(
            model_name="resourcerequestcounter",
            index=models.Index(fields=["date"], name="requestcounter_date_idx"),
        ),
    ]
