# Generated by Django 2.2.12 on 2020-04-08 15:15

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisation", "0030_auto_20200323_1142"),
    ]

    operations = [
        migrations.CreateModel(
            name="CAVLValidationTaskResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        db_index=True,
                        help_text="The ID for the Task that was run",
                        max_length=255,
                        unique=True,
                        verbose_name="Task ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FAILURE", "FAILURE"),
                            ("PENDING", "PENDING"),
                            ("RECEIVED", "RECEIVED"),
                            ("STARTED", "STARTED"),
                            ("SUCCESS", "SUCCESS"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current state of the task being run",
                        max_length=50,
                        verbose_name="Task State",
                    ),
                ),
                (
                    "completed",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Datetime field when the task was completed in UTC",
                        verbose_name="Completed DateTime",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organisation.DatasetRevision",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
