# Generated by Django 2.2.12 on 2020-04-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavlvalidationtaskresult",
            name="completed",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Datetime field when the task was completed in UTC",
                null=True,
                verbose_name="Completed DateTime",
            ),
        ),
    ]
