# Generated by Django 2.2.12 on 2020-06-09 15:30

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avl", "0004_data_fillresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="CAVLDataArchive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "last_updated",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="last_updated"
                    ),
                ),
                (
                    "data",
                    models.FileField(
                        help_text="A zip file containing an up to date siri vm XML.",
                        upload_to="",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "-created",
            },
        ),
    ]
