# Generated by Django 2.2.12 on 2020-09-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avl", "0005_cavldataarchive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavlvalidationtaskresult",
            name="result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VALID", "VALID"),
                    ("INVALID", "INVALID"),
                    ("SYSTEM_ERROR", "SYSTEM_ERROR"),
                    ("TIMEOUT_ERROR", "TIMEOUT_ERROR"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Task Result",
            ),
        ),
    ]
