# Generated by Django 2.2.12 on 2020-09-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avl", "0006_auto_20200901_1832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavlvalidationtaskresult",
            name="result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEED_VALID", "FEED_VALID"),
                    ("FEED_INVALID", "FEED_INVALID"),
                    ("SYSTEM_ERROR", "SYSTEM_ERROR"),
                    ("TIMEOUT_ERROR", "TIMEOUT_ERROR"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Task Result",
            ),
        ),
    ]
