# Generated by Django 2.2.12 on 2020-09-28 20:41

from django.db import migrations

import transit_odp.common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("avl", "0007_auto_20200915_1244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavldataarchive",
            name="data",
            field=transit_odp.common.fields.CallableStorageFileField(
                help_text="A zip file containing an up to date siri vm XML.",
                upload_to="",
            ),
        ),
    ]
