# Generated by Django 2.2.13 on 2020-12-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avl", "0009_callable_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="cavldataarchive",
            name="data_format",
            field=models.CharField(
                choices=[("VM", "Siri VM"), ("RT", "GTFS RT")],
                default="VM",
                max_length=2,
            ),
        ),
    ]
