# Generated by Django 2.2.22 on 2021-05-06 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("avl", "0010_cavldataarchive_data_format"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cavlvalidationtaskresult",
            options={"get_latest_by": "modified"},
        ),
    ]
