# Generated by Django 3.0.14 on 2021-08-12 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0046_added_licence_model"),
        ("avl", "0011_auto_20210506_1717"),
    ]

    operations = [
        migrations.CreateModel(
            name="AVLValidationReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "critical_count",
                    models.IntegerField(verbose_name="Number of critical issues"),
                ),
                (
                    "non_critical_count",
                    models.IntegerField(verbose_name="Number of non-critical issues"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="", verbose_name="AVL validation report file"
                    ),
                ),
                ("created", models.DateField(verbose_name="Creation date")),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avl_validation_reports",
                        to="organisation.DatasetRevision",
                    ),
                ),
            ],
        ),
    ]
