# Generated by Django 3.0.14 on 2021-08-12 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0046_added_licence_model"),
        ("avl", "0012_added_avl_report_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avlvalidationreport",
            name="critical_count",
            field=models.PositiveIntegerField(verbose_name="Number of critical issues"),
        ),
        migrations.AlterField(
            model_name="avlvalidationreport",
            name="non_critical_count",
            field=models.PositiveIntegerField(
                verbose_name="Number of non-critical issues"
            ),
        ),
        migrations.AlterField(
            model_name="avlvalidationreport",
            name="revision",
            field=models.ForeignKey(
                limit_choices_to={"dataset__dataset_type": 2},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avl_validation_reports",
                to="organisation.DatasetRevision",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="avlvalidationreport",
            unique_together={("revision", "created")},
        ),
    ]
