# Generated by Django 3.0.14 on 2021-08-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avl", "0014_added_limit_to_liverevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="avlvalidationreport",
            name="critical_score",
            field=models.FloatField(
                default=0, verbose_name="Score for critical observations"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avlvalidationreport",
            name="non_critical_score",
            field=models.FloatField(
                default=0, verbose_name="Score for non-critical observations"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="avlvalidationreport",
            name="vehicle_activity_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of VehicleActivity elements tested"
            ),
            preserve_default=False,
        ),
    ]
