# Generated by Django 3.0.14 on 2021-09-14 08:47

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0046_added_licence_model"),
        ("avl", "0015_added_scoring_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AVLSchemaValidationReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(verbose_name="Number of schema errors"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="", verbose_name="AVL schema validation report file"
                    ),
                ),
                ("created", models.DateField(verbose_name="Creation date")),
                (
                    "revision",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("dataset__dataset_type", 2),
                            (
                                "dataset__live_revision_id",
                                django.db.models.expressions.F("id"),
                            ),
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avl_schema_validation_reports",
                        to="organisation.DatasetRevision",
                    ),
                ),
            ],
            options={
                "unique_together": {("revision", "created")},
            },
        ),
    ]
