# Generated by Django 3.1.13 on 2021-09-30 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0046_added_licence_model"),
        ("avl", "0016_added_schema_validation_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="AVLDataset",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("organisation.dataset",),
        ),
    ]
