# Generated by Django 3.1.13 on 2021-11-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avl", "0017_avldataset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avlvalidationreport",
            name="file",
            field=models.FileField(
                null=True, upload_to="", verbose_name="AVL validation report file"
            ),
        ),
    ]
