# Generated by Django 3.1.14 on 2022-02-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avl", "0018_allow_no_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cavldataarchive",
            name="data_format",
            field=models.CharField(
                choices=[("VM", "Siri VM"), ("RT", "GTFS RT"), ("TL", "Siri VM TfL")],
                default="VM",
                max_length=2,
            ),
        ),
    ]
