# Generated by Django 3.1.14 on 2022-04-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0050_convert_expired_to_inactive"),
        ("avl", "0019_add_sirivm_tfl_data_archive_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="AVLDatasetRevision",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("organisation.datasetrevision",),
        ),
    ]
