# Generated by Django 3.2.13 on 2022-10-21 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0057_add_unique_together_contraint"),
        ("avl", "0020_add_avl_proxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostPublishingCheckReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(verbose_name="Creation date")),
                (
                    "granularity",
                    models.CharField(
                        choices=[("daily", "daily"), ("weekly", "weekly")],
                        max_length=6,
                        verbose_name="Daily or weekly",
                    ),
                ),
                ("file", models.FileField(upload_to="", verbose_name="PPC report")),
                (
                    "vehicle_activities_analysed",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Vehicles analysed"
                    ),
                ),
                (
                    "vehicle_activities_completely_matching",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Vehicles completely matching (ex. BlockRef)",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("dataset_type", 2)),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_ppc_reports",
                        to="organisation.dataset",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="postpublishingcheckreport",
            constraint=models.UniqueConstraint(
                fields=("dataset", "granularity", "created"), name="unique_report"
            ),
        ),
    ]
