# Generated by Django 4.2.14 on 2024-09-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avl", "0024_alter_cavlvalidationtaskresult_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AVLSchemaValidationReport",
        ),
    ]
