name: register_task_definition

inputs:
  service:
    required: true
  container:
    required: true
  environment:
    required: true
  image_id:
    required: true

runs:
  using: "composite"
  steps:
  - name: Render ECS task definition
    id: render-task-def
    uses: aws-actions/amazon-ecs-render-task-definition@6853cfae8c3a7d978fbf68b5a55453395541dfbb # 1.8.5
    with:
      task-definition-family: bodds_${{ inputs.service }}_${{ inputs.environment }}
      container-name: ${{ inputs.container }}
      image: ${{ inputs.image_id }}

  - name: Register task definition
    shell: bash
    run: |
      cat ${{ steps.render-task-def.outputs.task-definition }} | jq 'del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)' > ${{ github.workspace }}/updated-task-definition.json
      aws ecs register-task-definition --cli-input-json file://updated-task-definition.json
