# Generated by Django 2.2.5 on 2019-09-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("organisation", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="RemoteDatasetHealthCheckCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_retry_count",
                        to="organisation.DatasetRevision",
                    ),
                ),
            ],
        )
    ]
