# Generated by Django 2.2.5 on 2019-10-03 11:54

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_results", "0004_auto_20190516_0412"),
        ("organisation", "0006_auto_20191003_1254"),
        ("pipelines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetETLTaskResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("progress", models.IntegerField(verbose_name="Feed Progress")),
                (
                    "revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_results",
                        to="organisation.DatasetRevision",
                    ),
                ),
                (
                    "task_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_results.TaskResult",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DatasetETLErrors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("severe", "Severe"), ("minor", "Minor")],
                        max_length=255,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("xml", "Xml"),
                            ("zip", "Zip"),
                            ("naptan", "Naptan"),
                            ("unknown", "Unknown"),
                            ("data", "Data"),
                            ("availability", "Availability"),
                        ],
                        max_length=255,
                        verbose_name="Category",
                    ),
                ),
                ("description", models.CharField(max_length=8096)),
                (
                    "revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="organisation.DatasetRevision",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
