# Generated by Django 2.2.5 on 2019-10-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pipelines", "0002_datasetetlerrors_datasetetltaskresult")]

    operations = [
        migrations.AlterField(
            model_name="datasetetltaskresult",
            name="revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etl_results",
                to="organisation.DatasetRevision",
            ),
        )
    ]
