# Generated by Django 2.2.5 on 2019-10-03 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0006_auto_20191003_1254"),
        ("pipelines", "0003_auto_20191003_1312"),
    ]

    operations = [
        migrations.RenameModel(old_name="DatasetETLErrors", new_name="DatasetETLError")
    ]
