# Generated by Django 2.2.7 on 2019-11-22 12:45

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0020_remove_datasetrevision_line_names"),
        ("data_quality", "0018_auto_20191120_1732"),
        ("pipelines", "0006_auto_20191009_1415"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataQualityTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "task_id",
                    models.UUIDField(
                        help_text="The task_id returned by DQS when the task has been successfully received",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FAILURE", "FAILURE"),
                            ("PENDING", "PENDING"),
                            ("RECEIVED", "RECEIVED"),
                            ("STARTED", "STARTED"),
                            ("SUCCESS", "SUCCESS"),
                        ],
                        default="PENDING",
                        help_text="Current state of the task being run",
                        max_length=50,
                        verbose_name="Task State",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        help_text="The DQS report returned by DQS when the task has finished",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data_quality.DataQualityReport",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_quality_tasks",
                        to="organisation.DatasetRevision",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
