# Generated by Django 2.2.7 on 2019-11-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0007_dataqualitytask"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataqualitytask",
            name="message",
            field=models.TextField(
                default="", help_text="Contains more details about the DQS job"
            ),
        ),
        migrations.AlterField(
            model_name="dataqualitytask",
            name="task_id",
            field=models.UUIDField(
                help_text="The task_id returned by DQS when the task has been successfully received",
                null=True,
                unique=True,
            ),
        ),
    ]
