# Generated by Django 2.2.8 on 2019-12-08 20:56

from django.db import migrations
from django.db.models import F, OuterRef, Subquery
from django_celery_results.models import TaskResult


def fill_task_id(apps, schema_editor):
    """
    This data migration fills the task_id field on DatasetETLTaskResult using the existing (Celery) task_id of the
    related CeleryTaskResult. The next migration will remove the CeleryTaskResult relation.
    """
    DatasetETLTaskResult = apps.get_model("pipelines", "DatasetETLTaskResult")
    DatasetETLTaskResult.objects.update(
        task_id=Subquery(
            TaskResult.objects.filter(pk=OuterRef("task_result")).values("task_id")[:1]
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0009_auto_20191208_2055"),
    ]

    operations = [
        migrations.RunPython(fill_task_id, migrations.RunPython.noop, elidable=True)
    ]
