# Generated by Django 2.2.8 on 2019-12-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0010_data_migration_fill_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasetetltaskresult",
            name="task_result",
        ),
        migrations.AlterField(
            model_name="datasetetltaskresult",
            name="task_id",
            field=models.CharField(
                db_index=True,
                help_text="The ID for the Task that was run",
                max_length=255,
                unique=True,
                verbose_name="Task ID",
            ),
        ),
    ]
