# Generated by Django 2.2.8 on 2019-12-10 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0012_auto_20191209_2304"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dataqualitytask",
            options={
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
            },
        ),
        migrations.AlterModelOptions(
            name="datasetetltaskresult",
            options={
                "get_latest_by": "modified",
                "ordering": ("-modified", "-created"),
            },
        ),
    ]
