# Generated by Django 2.2.12 on 2020-04-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0014_auto_20191223_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataqualitytask",
            name="completed",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Datetime field when the task was completed in UTC",
                null=True,
                verbose_name="Completed DateTime",
            ),
        ),
        migrations.AlterField(
            model_name="datasetetltaskresult",
            name="completed",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Datetime field when the task was completed in UTC",
                null=True,
                verbose_name="Completed DateTime",
            ),
        ),
    ]
