# Generated by Django 2.2.12 on 2020-09-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0016_bulkdataarchive_dataset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetetltaskresult",
            name="additional_info",
            field=models.CharField(
                blank=True,
                help_text="Additional information about a failed task",
                max_length=512,
                null=True,
                verbose_name="Additional Information",
            ),
        ),
    ]
