# Generated by Django 2.2.22 on 2021-05-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0017_datasetetltaskresult_additional_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dataqualitytask",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="datasetetlerror",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="datasetetltaskresult",
            options={"get_latest_by": "modified"},
        ),
    ]
