# Generated by Django 2.2.23 on 2021-06-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0018_auto_20210506_1717"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkdataarchive",
            name="compliant_archive",
            field=models.BooleanField(
                default=False, verbose_name="Whether all the datasets are compliant."
            ),
        ),
    ]
