# Generated by Django 3.1.9 on 2021-11-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0019_add_compliant_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkdataarchive",
            name="traveline_regions",
            field=models.CharField(
                choices=[
                    ("ALL", "All"),
                    ("EA", "East Anglia"),
                    ("EM", "East Midlands"),
                    ("L", "London"),
                    ("NE", "North East"),
                    ("NW", "North West"),
                    ("S", "Scotland"),
                    ("SE", "South East"),
                    ("SW", "South West"),
                    ("W", "Wales"),
                    ("WM", "West Midlands"),
                    ("Y", "Yorkshire"),
                ],
                default="ALL",
                max_length=4,
                verbose_name="TravelineRegion",
            ),
        ),
    ]
