# Generated by Django 3.2.13 on 2022-09-08 10:42

import django.core.validators
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0020_added_traveline_region_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("txc", "TxC"), ("netex", "NeTeX")],
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("checksum", models.CharField(max_length=40)),
                (
                    "schema",
                    models.FileField(
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator([".zip"])
                        ],
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
