# Generated by Django 4.2.14 on 2024-10-30 10:44

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0025_alter_datasetetltaskresult_error_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineErrorCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error",
                    models.CharField(
                        choices=[
                            ("DANGEROUS_XML_ERROR", "DANGEROUS_XML_ERROR"),
                            ("DATASET_EXPIRED", "DATASET_EXPIRED"),
                            ("FILE_TOO_LARGE", "FILE_TOO_LARGE"),
                            ("NESTED_ZIP_FORBIDDEN", "NESTED_ZIP_FORBIDDEN"),
                            ("NO_DATA_FOUND", "NO_DATA_FOUND"),
                            ("NO_VALID_FILE_TO_PROCESS", "NO_VALID_FILE_TO_PROCESS"),
                            ("POST_SCHEMA_ERROR", "POST_SCHEMA_ERROR"),
                            ("SCHEMA_ERROR", "SCHEMA_ERROR"),
                            ("SCHEMA_VERSION_MISSING", "SCHEMA_VERSION_MISSING"),
                            (
                                "SCHEMA_VERSION_NOT_SUPPORTED",
                                "SCHEMA_VERSION_NOT_SUPPORTED",
                            ),
                            ("SUSPICIOUS_FILE", "SUSPICIOUS_FILE"),
                            ("SYSTEM_ERROR", "SYSTEM_ERROR"),
                            ("XML_SYNTAX_ERROR", "XML_SYNTAX_ERROR"),
                            ("ZIP_TOO_LARGE", "ZIP_TOO_LARGE"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "pipelines_pipelineerrorcode",
            },
        ),
        migrations.CreateModel(
            name="PipelineProcessingStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[("FARES", "FARES"), ("TIMETABLES", "TIMETABLES")],
                        default="TIMETABLES",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "pipelines_pipelineprocessingstep",
            },
        ),
        migrations.AlterField(
            model_name="dataqualitytask",
            name="status",
            field=models.CharField(
                choices=[
                    ("ERROR", "ERROR"),
                    ("FAILURE", "FAILURE"),
                    ("PENDING", "PENDING"),
                    ("READY", "READY"),
                    ("RECEIVED", "RECEIVED"),
                    ("STARTED", "STARTED"),
                    ("SUCCESS", "SUCCESS"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Current state of the task being run",
                max_length=50,
                verbose_name="Task State",
            ),
        ),
        migrations.AlterField(
            model_name="datasetetltaskresult",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DANGEROUS_XML_ERROR", "DANGEROUS_XML_ERROR"),
                    ("DATASET_EXPIRED", "DATASET_EXPIRED"),
                    ("FILE_TOO_LARGE", "FILE_TOO_LARGE"),
                    ("NESTED_ZIP_FORBIDDEN", "NESTED_ZIP_FORBIDDEN"),
                    ("NO_DATA_FOUND", "NO_DATA_FOUND"),
                    ("NO_VALID_FILE_TO_PROCESS", "NO_VALID_FILE_TO_PROCESS"),
                    ("POST_SCHEMA_ERROR", "POST_SCHEMA_ERROR"),
                    ("SCHEMA_ERROR", "SCHEMA_ERROR"),
                    ("SCHEMA_VERSION_MISSING", "SCHEMA_VERSION_MISSING"),
                    ("SCHEMA_VERSION_NOT_SUPPORTED", "SCHEMA_VERSION_NOT_SUPPORTED"),
                    ("SUSPICIOUS_FILE", "SUSPICIOUS_FILE"),
                    ("SYSTEM_ERROR", "SYSTEM_ERROR"),
                    ("XML_SYNTAX_ERROR", "XML_SYNTAX_ERROR"),
                    ("ZIP_TOO_LARGE", "ZIP_TOO_LARGE"),
                ],
                db_index=True,
                help_text="The error code returned for the failed task",
                max_length=50,
                verbose_name="Task Error Code",
            ),
        ),
        migrations.AlterField(
            model_name="datasetetltaskresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("ERROR", "ERROR"),
                    ("FAILURE", "FAILURE"),
                    ("PENDING", "PENDING"),
                    ("READY", "READY"),
                    ("RECEIVED", "RECEIVED"),
                    ("STARTED", "STARTED"),
                    ("SUCCESS", "SUCCESS"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Current state of the task being run",
                max_length=50,
                verbose_name="Task State",
            ),
        ),
        migrations.CreateModel(
            name="FileProcessingResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        db_index=True,
                        help_text="The ID for the Task that was run",
                        max_length=255,
                        unique=True,
                        verbose_name="Task ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ERROR", "ERROR"),
                            ("FAILURE", "FAILURE"),
                            ("PENDING", "PENDING"),
                            ("READY", "READY"),
                            ("RECEIVED", "RECEIVED"),
                            ("STARTED", "STARTED"),
                            ("SUCCESS", "SUCCESS"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current state of the task being run",
                        max_length=50,
                        verbose_name="Task State",
                    ),
                ),
                (
                    "completed",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Datetime field when the task was completed in UTC",
                        null=True,
                        verbose_name="Completed DateTime",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "pipeline_error_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_processing_errors",
                        to="pipelines.pipelineerrorcode",
                    ),
                ),
                (
                    "pipeline_processing_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_processing_steps",
                        to="pipelines.pipelineprocessingstep",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_processing_results",
                        to="organisation.datasetrevision",
                    ),
                ),
            ],
            options={
                "db_table": "pipelines_fileprocessingresult",
            },
        ),
    ]
