# Generated by Django 4.2.23 on 2026-08-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0026_pipelineerrorcode_pipelineprocessingstep_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetetltaskresult",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ANTIVIRUS_FAILURE", "ANTIVIRUS_FAILURE"),
                    ("AV_CONNECTION_ERROR", "AV_CONNECTION_ERROR"),
                    ("DANGEROUS_XML_ERROR", "DANGEROUS_XML_ERROR"),
                    ("DATASET_EXPIRED", "DATASET_EXPIRED"),
                    ("FILE_TOO_LARGE", "FILE_TOO_LARGE"),
                    ("NESTED_ZIP_FORBIDDEN", "NESTED_ZIP_FORBIDDEN"),
                    ("NO_DATA_FOUND", "NO_DATA_FOUND"),
                    ("NO_VALID_FILE_TO_PROCESS", "NO_VALID_FILE_TO_PROCESS"),
                    ("POST_SCHEMA_ERROR", "POST_SCHEMA_ERROR"),
                    ("SCHEMA_ERROR", "SCHEMA_ERROR"),
                    ("SCHEMA_VERSION_MISSING", "SCHEMA_VERSION_MISSING"),
                    ("SCHEMA_VERSION_NOT_SUPPORTED", "SCHEMA_VERSION_NOT_SUPPORTED"),
                    ("SUSPICIOUS_FILE", "SUSPICIOUS_FILE"),
                    ("SYSTEM_ERROR", "SYSTEM_ERROR"),
                    ("XML_SYNTAX_ERROR", "XML_SYNTAX_ERROR"),
                    ("ZIP_TOO_LARGE", "ZIP_TOO_LARGE"),
                ],
                db_index=True,
                help_text="The error code returned for the failed task",
                max_length=50,
                verbose_name="Task Error Code",
            ),
        ),
        migrations.AlterField(
            model_name="schemadefinition",
            name="category",
            field=models.CharField(
                choices=[("txc", "TxC"), ("txc241", "TxC 2.4.1"), ("netex", "NeTeX")],
                max_length=6,
                unique=True,
            ),
        ),
    ]
