# Generated by Django 3.2.13 on 2022-11-30 16:09

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    replaces = [('fares_validator', '0001_initial'), ('fares_validator', '0002_auto_20221128_1434'), ('fares_validator', '0003_auto_20221130_1206')]

    initial = True

    dependencies = [
        ('organisation', '0054_initialise_organisation_stats'),
        ('organisation', '0057_add_unique_together_contraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaresValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(help_text='Number of fare violations.')),
                ('report_file_name', models.CharField(help_text='The name of the report file.', max_length=256)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('revision', models.OneToOneField(help_text='The revision being validated.', on_delete=django.db.models.deletion.CASCADE, related_name='fares_validation_result', to='organisation.datasetrevision')),
                ('organisation', models.ForeignKey(default=1, help_text='Bus portal organisation.', on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='FaresValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='The name of the file the observation occurs in.', max_length=256)),
                ('error_line_no', models.IntegerField(help_text='The line number of the observation.')),
                ('type_of_observation', models.CharField(help_text='Type Of Observation', max_length=1024)),
                ('category', models.CharField(help_text='The category of the observation.', max_length=1024)),
                ('error', models.CharField(help_text='The detailed error of the observation.', max_length=2000)),
                ('reference', models.CharField(default='Please see BODS Fares Validator Guidance v0.2', help_text='The reference of the observation', max_length=1024)),
                ('important_note', models.CharField(default='Data containing this warning will be rejected by BODS after January 2023. Please contact your ticket machine supplier', help_text='The Important Note error of the observation.', max_length=2000)),
                ('organisation', models.ForeignKey(help_text='Bus portal organisation.', on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
                ('revision', models.ForeignKey(default=1, help_text='The revision that validation occurred in.', on_delete=django.db.models.deletion.CASCADE, related_name='fares_validations', to='organisation.datasetrevision')),
            ],
        ),
    ]
