# Generated by Django 3.2.16 on 2022-12-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fares_validator", "0002_auto_20221130_1650"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faresvalidation",
            name="important_note",
            field=models.CharField(
                default="This is warning only but data containing this failure will eventually be rejected by BODS ",
                help_text="The Important Note error of the observation.",
                max_length=2000,
            ),
        ),
    ]
