# Generated by Django 3.2.13 on 2022-11-30 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0057_add_unique_together_contraint"),
        ("fares_validator", "0002_auto_20221128_1434"),
    ]

    operations = [
        migrations.AddField(
            model_name="faresvalidationresult",
            name="organisation",
            field=models.ForeignKey(
                default=1,
                help_text="Bus portal organisation.",
                on_delete=django.db.models.deletion.CASCADE,
                to="organisation.organisation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="faresvalidation",
            name="reference",
            field=models.CharField(
                default="Please see BODS Fares Validator Guidance v0.2",
                help_text="The reference of the observation",
                max_length=1024,
            ),
        ),
    ]
