# coding: utf-8

"""
    CAVL Config API

    Used to configure feed consumers in the CAVL Service  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: greg.brown@itoworld.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cavl_client
from cavl_client.rest import ApiException


class TestInlineResponse201(unittest.TestCase):
    """InlineResponse201 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse201(self):
        """Test InlineResponse201"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cavl_client.models.inline_response201.InlineResponse201()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
