# coding: utf-8

"""
    CAVL Config API

    Used to configure feed consumers in the CAVL Service  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: greg.brown@itoworld.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cavl_client
from cavl_client.rest import ApiException

# class TestValidateApi(unittest.TestCase):
#     """ValidateApi unit test stubs"""
#
#     def setUp(self):
#         self.api = api.validate_api.ValidateApi()  # noqa: E501
#
#     def tearDown(self):
#         pass
#
#     def test_validate_feed(self):
#         """Test case for validate_feed
#
#         Creates a validation task to validate a feed  # noqa: E501
#         """
#         pass


if __name__ == "__main__":
    unittest.main()
