# coding: utf-8

"""
    CAVL Config API

    Used to configure feed consumers in the CAVL Service  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: greg.brown@itoworld.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cavl_client
from cavl_client.rest import ApiException


class TestFeed:
    def test_account_key_write_only(self):
        """Tests the Feed model can be instantiated without account_key

        The `account_key` is required in the Swagger spec in the request body but is marked as writeOnly.
        Therefore, it shouldn't throw a validation error for responses.
        """
        # Setup

        # Test
        model = cavl_client.models.feed.Feed(
            id=1,
            publisher_id=10,
            url="http://www.test-feed.com",
            username="acccount123",
            # No password
        )

        assert model.password is None
