# Generated by Django 2.2.5 on 2019-09-30 08:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("invitations", "0003_auto_20151126_1523"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "invitation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="invitations.Invitation",
                    ),
                ),
                (
                    "account_type",
                    models.IntegerField(
                        choices=[
                            (1, "Site Admin"),
                            (2, "Organisation Admin"),
                            (3, "Organisation Staff"),
                            (4, "Developer"),
                        ],
                        default=4,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The account is tied to this organisation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisation.Organisation",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("invitations.invitation", models.Model),
        )
    ]
