# Generated by Django 2.2.6 on 2019-10-25 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_invitation_model")]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mute_all_dataset_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Mute all feed notifications"
                    ),
                ),
                (
                    "notify_on_expiring_dataset",
                    models.BooleanField(
                        default=False, verbose_name="Published data expiry reminder"
                    ),
                ),
                (
                    "notify_invitation_accepted",
                    models.BooleanField(
                        default=False, verbose_name="Team members accept invitation"
                    ),
                ),
            ],
        )
    ]
