# Generated by Django 2.2.6 on 2019-10-25 11:31
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def populate_mute_all_dataset_notifications(apps, schema_editor):
    logger.info(
        "Migrating user.mute_notifications to user.settings.mute_all_dataset_notifications"
    )
    User = apps.get_model("users", "User")
    UserSettings = apps.get_model("users", "UserSettings")
    settings = []

    for user in User.objects.all():
        mute = user.mute_notifications
        settings.append(UserSettings(user=user, mute_all_dataset_notifications=mute))
    UserSettings.objects.bulk_create(settings)


class Migration(migrations.Migration):
    dependencies = [("users", "0003_usersettings")]

    operations = [migrations.RunPython(populate_mute_all_dataset_notifications)]
