# Generated by Django 2.2.6 on 2019-10-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20191025_1231")]

    operations = [migrations.RemoveField(model_name="user", name="mute_notifications")]
