# Generated by Django 2.2.7 on 2019-12-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_mute_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privacy_consent",
            field=models.BooleanField(default=False),
        ),
    ]
