# Generated by Django 2.2.12 on 2020-04-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_invitation_is_key_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="privacy_consent",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="opt_in_user_research",
            field=models.BooleanField(
                default=False, verbose_name="Opt in for user research"
            ),
        ),
    ]
