# Generated by Django 2.2.12 on 2020-05-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20200421_1623"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Intended use for the API"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dev_organisation",
            field=models.CharField(
                blank=True, max_length=55, verbose_name="Developer organisation"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="share_app_usage",
            field=models.BooleanField(
                default=False, verbose_name="Share app usage with DFT"
            ),
        ),
    ]
