# Generated by Django 2.2.13 on 2020-07-16 15:34
import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def populate_organisations_for_users(apps, schema_editor):
    logger.info("Migrating foreignkey organisation to many to many field organisations")
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if user.organisation is not None:
            user.organisations.add(user.organisation)


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0034_datasetmetadata"),
        ("users", "0009_auto_20200528_1302"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organisations",
            field=models.ManyToManyField(
                related_name="users", to="organisation.Organisation"
            ),
        ),
        migrations.RunPython(populate_organisations_for_users),
    ]
