# Generated by Django 2.2.12 on 2020-07-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_organisations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organisation",
        ),
    ]
