# Generated by Django 2.2.12 on 2020-08-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_user_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="account_type",
            field=models.IntegerField(
                choices=[
                    (1, "Site Admin"),
                    (2, "Organisation Admin"),
                    (3, "Organisation Staff"),
                    (4, "Developer"),
                    (5, "Agent User"),
                ],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.IntegerField(
                choices=[
                    (1, "Site Admin"),
                    (2, "Organisation Admin"),
                    (3, "Organisation Staff"),
                    (4, "Developer"),
                    (5, "Agent User"),
                ],
                default=4,
            ),
        ),
    ]
