# Generated by Django 2.2.13 on 2020-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_agentuserinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="notify_avl_unavailable",
            field=models.BooleanField(
                default=False, verbose_name="Published AVL feed unavailable alert"
            ),
        ),
    ]
