# Generated by Django 2.2.13 on 2020-10-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_usersettings_notify_on_expiring_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent_organisation",
            field=models.CharField(
                blank=True, max_length=55, verbose_name="Agent user organisation"
            ),
        ),
    ]
