# Generated by Django 2.2.13 on 2020-10-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_user_agent_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentuserinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("inactive", "Inactive"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
