# Generated by Django 2.2.13 on 2020-11-20 13:59

from django.db import migrations, models

import transit_odp.common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_auto_20201009_0927"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notes",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[transit_odp.common.validators.validate_profanity],
                verbose_name="Notes about a user",
            ),
        ),
    ]
