# Generated by Django 3.1.13 on 2021-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_daily_compliance_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
