# Generated by Django 3.1.13 on 2021-10-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_auto_20210930_1524"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="intended_use",
            field=models.IntegerField(
                choices=[
                    (1, "App"),
                    (2, "Research"),
                    (3, "Digital Signage"),
                    (4, "Website / Portal"),
                    (5, "Local Transport Authority"),
                    (6, "Personal interests or other"),
                ],
                default=1,
                null=True,
                verbose_name="What best describes intended use",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="national_interest",
            field=models.BooleanField(
                blank=True,
                default=True,
                null=True,
                verbose_name="Interested in national rather than regional data",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="regional_areas",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Regional areas of interest"
            ),
        ),
    ]
