# Generated by Django 3.1.13 on 2021-10-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_add_national_interest_and_intended_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="agent_organisation",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Agent user organisation"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(
                blank=True, max_length=400, verbose_name="Intended use for the API"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="dev_organisation",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Developer organisation"
            ),
        ),
    ]
