# Generated by Django 4.2.14 on 2025-04-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_extend_text_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="account_type",
            field=models.IntegerField(
                choices=[
                    (1, "Site Admin"),
                    (2, "Organisation Admin"),
                    (3, "Organisation Staff"),
                    (4, "Developer"),
                    (5, "Agent User"),
                    (6, "Abods Only"),
                ],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.IntegerField(
                choices=[
                    (1, "Site Admin"),
                    (2, "Organisation Admin"),
                    (3, "Organisation Staff"),
                    (4, "Developer"),
                    (5, "Agent User"),
                    (6, "Abods Only"),
                ],
                default=4,
            ),
        ),
    ]
