# Generated by Django 3.2.13 on 2022-07-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("page_url", models.CharField(max_length=2048)),
                (
                    "satisfaction_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very satisfied"),
                            (2, "Satisfied"),
                            (3, "Neither satisfied nor dissatisfied"),
                            (4, "Dissatisfied"),
                            (5, "Very dissatisfied"),
                        ]
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=1200)),
            ],
        ),
    ]
