from django.urls import include, path
from django.views.generic import RedirectView

from transit_odp.site_admin.views import (
    BulkResendInviteView,
    InviteSuccessView,
    InviteView,
    OrganisationArchiveSuccessView,
    OrganisationArchiveView,
    OrganisationAVLListView,
    OrganisationCreateSuccessView,
    OrganisationCreateView,
    OrganisationDetailView,
    OrganisationEditSuccessView,
    OrganisationEditView,
    OrganisationFaresListView,
    OrganisationListView,
    OrganisationTimetableListView,
    OrganisationUsersManageView,
    RemoveAgentUserSuccessView,
    RemoveAgentUserView,
    ResendAgentUserInviteSuccessView,
    ResendAgentUserInviteView,
    ResendInvitationView,
    ResendInviteSuccessView,
    ResendOrgUserInviteSuccessView,
    ResendOrgUserInviteView,
    UserArchiveSuccessView,
    UserDetailView,
    UserEditSuccessView,
    UserEditView,
    UserIsActiveView,
)

_agent_invite_paths = [
    path(
        "resend/",
        include(
            [
                path(
                    "",
                    view=ResendAgentUserInviteView.as_view(),
                    name="org-resend-agent-invite",
                ),
                path(
                    "success/",
                    view=ResendAgentUserInviteSuccessView.as_view(),
                    name="org-resend-agent-invite-success",
                ),
            ]
        ),
    ),
]


_user_paths = [
    path(
        "",
        view=OrganisationUsersManageView.as_view(),
        name="org-user-manage",
    ),
    path(
        "<int:pk1>/",
        include(
            [
                path(
                    "",
                    view=UserDetailView.as_view(),
                    name="manage-user-detail",
                ),
                path(
                    "edit/",
                    include(
                        [
                            path(
                                "",
                                view=UserEditView.as_view(),
                                name="manage-user-edit",
                            ),
                            path(
                                "success",
                                view=UserEditSuccessView.as_view(),
                                name="manage-user-edit-success",
                            ),
                        ]
                    ),
                ),
                path(
                    "re-invite/",
                    include(
                        [
                            path(
                                "",
                                view=ResendOrgUserInviteView.as_view(),
                                name="manage-user-re-invite",
                            ),
                            path(
                                "success/",
                                view=ResendOrgUserInviteSuccessView.as_view(),
                                name="manage-user-re-invite-success",
                            ),
                        ]
                    ),
                ),
                path(
                    "archive/",
                    include(
                        [
                            path(
                                "",
                                view=UserIsActiveView.as_view(),
                                name="org-user-archive",
                            ),
                            path(
                                "success/",
                                view=UserArchiveSuccessView.as_view(),
                                name="org-user-archive-success",
                            ),
                        ]
                    ),
                ),
                path(
                    "activate/",
                    view=UserIsActiveView.as_view(),
                    name="org-user-activate",
                ),
                path(
                    "agent/<int:invite_id>/remove/",
                    include(
                        [
                            path(
                                "",
                                view=RemoveAgentUserView.as_view(),
                                name="org-remove-agent",
                            ),
                            path(
                                "success/",
                                view=RemoveAgentUserSuccessView.as_view(),
                                name="org-remove-agent-success",
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
    path(
        "invite/",
        include(
            [
                path(
                    "",
                    view=InviteView.as_view(),
                    name="org-user-invite",
                ),
                path(
                    "success/",
                    view=InviteSuccessView.as_view(),
                    name="org-user-invite-success",
                ),
            ]
        ),
    ),
]

_organisation_paths = [
    path(
        "",
        view=OrganisationDetailView.as_view(),
        name="organisation-detail",
    ),
    path("users/", include(_user_paths)),
    path("agent/<int:invite_id>/", include(_agent_invite_paths)),
    path(
        "edit/",
        include(
            [
                path(
                    "",
                    view=OrganisationEditView.as_view(),
                    name="organisation-update",
                ),
                path(
                    "success/",
                    view=OrganisationEditSuccessView.as_view(),
                    name="edit-organisation-success",
                ),
            ]
        ),
    ),
    path(
        "archive/",
        include(
            [
                path(
                    "",
                    view=OrganisationArchiveView.as_view(),
                    name="organisation-archive",
                ),
                path(
                    "success/",
                    view=OrganisationArchiveSuccessView.as_view(),
                    name="organisation-archive-success",
                ),
            ]
        ),
    ),
    path(
        "re-invite/",
        include(
            [
                path(
                    "",
                    view=ResendInvitationView.as_view(),
                    name="re-invite",
                ),
                path(
                    "success/",
                    view=ResendInviteSuccessView.as_view(),
                    name="re-invite-success",
                ),
            ]
        ),
    ),
    path(
        "success/",
        view=OrganisationCreateSuccessView.as_view(),
        name="create-organisation-success",
    ),
    path(
        "timetables/",
        view=OrganisationTimetableListView.as_view(),
        name="organisation-timetables-list",
    ),
    path(
        "avl/",
        view=OrganisationAVLListView.as_view(),
        name="organisation-avl-list",
    ),
    path(
        "fares/",
        view=OrganisationFaresListView.as_view(),
        name="organisation-fares-list",
    ),
]

paths = [
    path(
        "",
        view=OrganisationListView.as_view(),
        name="organisation-manage",
    ),
    path("<int:pk>/", include(_organisation_paths)),
    path(
        "new/",
        view=OrganisationCreateView.as_view(),
        name="organisation-new",
    ),
    path(
        "bulk-resend-invite",
        view=BulkResendInviteView.as_view(),
        name="bulk-resend-invite",
    ),
    path(
        "search/",
        view=RedirectView.as_view(pattern_name="users:organisation-manage"),
        name="organisation-search",
    ),
]
