openapi: 3.0.0
info:
  description: |
    You can use the interactive documentation
    to customise your API response using the available query parameters.
    If you are registered and logged in, you will be given a full response.
    Otherwise you will be given an example response.

    ## Ready to use the API?

    [View developer documentation](/guidance/requirements/?section=api)

    ## First time API user?

    [Guide me](/guide-me/)

  title: Fares data API
  version: 1.0.0

tags:
  - name: Data set
    description: Interact with fares datasets

paths:
  /api/v1/fares/dataset:
    get:
      tags:
        - Data set
      description: Returns all fares datasets
      summary: Find fares

      parameters:
        - name: noc
          in: query
          description: |
            Operators can operate using a single National Operator Codes (NOC)
            or have multiple NOC associated with it. Download
            [data catalogue](/catalogue/) to see the relationship between operators and NOC
            within the service.
            Input a comma separated list of NOC to limit results to the operators
            associated with the NOC provided.
          schema:
            type: array
            items:
              type: string
            example: [SCGH, SCLI]
          style: form
          explode: false

        - name: status
          in: query
          description: Limit results to data sets with the specified status
            string, accepted values are published, inactive.
          schema:
            type: string
            example: published
            enum:
              - published
              - inactive

        - name: boundingBox
          in: query
          schema:
            type: array
            items:
              type: number
            minItems: 4
            maxItems: 4
            example: [-2.930, 53.374, -3.085, 53.453]
          description: >
            Limit results to fares data sets that contain information for the area within the rectangular boundingBox you set using co-ordinates.
            [minLatitude, maxLatitude, minLongitude, maxLongitude]. The default values shown are for the Liverpool area.

        - name: limit
          in: query
          description: The maximum number of records to return. The default value shown is 25.
          schema:
            type: integer
            format: int64
            maximum: 100
            example: 25

        - name: offset
          in: query
          description:
            Return results that match the query starting from the specified offset.
            e.g. If the offset=10 and limit=25, then results from 11 to 36 will be returned
            The default value shown is 0.
          schema:
            type: integer
            format: int64
            maximum: 100
            example: 0

      responses: {}

  /api/v1/fares/dataset/{datasetID}:
    get:
      tags:
        - Data set
      summary: Find a fares dataset by ID
      description: Returns a single dataset
      parameters:
        - name: datasetID
          in: path
          description: (path)</br>limit results to a specific data feed of a publisher using the data feed ID.
          required: true
          schema:
            type: integer
            format: int64
            example: 86
      responses: {}

components:
  schemas:
    FaresResponse:
      type: object
      properties:
        count:
          type: integer
          format: int64
          example: 2345
        next:
          type: uri
          nullable: true
          example: https://data.bus-data.dft.gov.uk/api/v1/fares/dataset/?limit=25&offset=50
        previous:
          type: uri
          nullable: true
          example: https://data.bus-data.dft.gov.uk/api/v1/fares/dataset/?limit=25&offset=25
        results:
          type: array
          items:
            $ref: "#/components/schemas/Fares"
    Fares:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        created:
          type: string
          format: date-time
          example: "2021-01-01T12:45:00"
        modified:
          type: string
          format: date-time
          example: "2021-01-01T12:45:00"
        operatorName:
          type: string
          example: Stagecoach
        noc:
          type: array
          items:
            type: string
            example: [BDNY, CLTL]
        name:
          type: string
          example: Stagecoach_Stockport_Manchester City Centre_20200828"
        description:
          type: string
          example: Stagecoach Manchester
        comment:
          type: string
          example: Automatically detected change in data set
        status:
          type: string
          enum: [published, error, inactive]
          example: inactive
        url:
          type: string
          format: uri
          example: https://data.bus-data.dft.gov.uk/fares/dataset/6/download/
        extension:
          type: string
          example: zip
        startDate:
          type: string
          format: date-time
          example: "2020-08-28T00:00:00+00:00"
        endDate:
          type: string
          format: date-time
          example: "2020-11-28T23:59:00+00:00"
        numOfLines:
          type: integer
          format: int64
          example: 5
        numOfFareZones:
          type: integer
          format: int64
          example: 8
        numOfSalesOfferPackages:
          type: integer
          format: int64
          example: 1
        numOfFareProducts:
          type: integer
          format: int64
          example: 1
        numOfUserTypes:
          type: integer
          format: int64
          example: 4
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          example: "Not found"
