# Generated by Django 2.2.7 on 2019-11-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_quality",
            "0005_fastlinkwarning_fasttimingwarning_firststopnottimingwarning_firststopsetdownonlywarning_journeydupli",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stoppoint",
            options={},
        ),
        migrations.RemoveField(
            model_name="servicepattern",
            name="report",
        ),
        migrations.AlterUniqueTogether(
            name="servicelink",
            unique_together={("from_stop", "to_stop")},
        ),
        migrations.AlterUniqueTogether(
            name="stoppoint",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="servicelink",
            name="report",
        ),
        migrations.RemoveField(
            model_name="stoppoint",
            name="report",
        ),
    ]
