# Generated by Django 2.2.7 on 2019-11-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0006_auto_20191114_1003"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stoppoint",
            old_name="location",
            new_name="geometry",
        ),
    ]
