# Generated by Django 2.2.7 on 2019-11-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0009_auto_20191118_1029"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="report",
        ),
        migrations.AddField(
            model_name="service",
            name="ito_id",
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="reports",
            field=models.ManyToManyField(
                related_name="services", to="data_quality.DataQualityReport"
            ),
        ),
        migrations.AddField(
            model_name="servicelink",
            name="ito_id",
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicepattern",
            name="ito_id",
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timingpattern",
            name="ito_id",
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehiclejourney",
            name="ito_id",
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
