# Generated by Django 2.2.7 on 2019-11-18 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0011_stoppoint_ito_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelink",
            name="geometry",
            field=django.contrib.gis.db.models.fields.LineStringField(
                null=True, srid=4326
            ),
        ),
    ]
