# Generated by Django 2.2.7 on 2019-11-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0012_servicelink_geometry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicelinkmissingstopwarning",
            name="stops",
        ),
        migrations.AddField(
            model_name="servicelinkmissingstopwarning",
            name="stops",
            field=models.ManyToManyField(to="data_quality.StopPoint"),
        ),
    ]
