# Generated by Django 2.2.7 on 2019-11-19 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0013_auto_20191118_2343"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicepatternstop",
            old_name="sequence_number",
            new_name="position",
        ),
        migrations.AlterUniqueTogether(
            name="servicepatternstop",
            unique_together={("service_pattern", "stop", "position")},
        ),
    ]
