# Generated by Django 2.2.7 on 2019-11-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0015_auto_20191119_1808"),
    ]

    operations = [
        migrations.AddField(
            model_name="fastlinkwarning",
            name="timings",
            field=models.ManyToManyField(to="data_quality.TimingPatternStop"),
        ),
        migrations.AddField(
            model_name="fasttimingwarning",
            name="timings",
            field=models.ManyToManyField(to="data_quality.TimingPatternStop"),
        ),
        migrations.AddField(
            model_name="firststopsetdownonlywarning",
            name="timings",
            field=models.ManyToManyField(to="data_quality.TimingPatternStop"),
        ),
        migrations.AddField(
            model_name="laststoppickuponlywarning",
            name="timings",
            field=models.ManyToManyField(to="data_quality.TimingPatternStop"),
        ),
        migrations.AddField(
            model_name="multiplestopswarning",
            name="timings",
            field=models.ManyToManyField(to="data_quality.TimingPatternStop"),
        ),
        migrations.AddField(
            model_name="slowlinkwarning",
            name="timings",
            field=models.ManyToManyField(to="data_quality.TimingPatternStop"),
        ),
        migrations.AddField(
            model_name="slowtimingwarning",
            name="timings",
            field=models.ManyToManyField(to="data_quality.TimingPatternStop"),
        ),
    ]
