# Generated by Django 2.2.7 on 2019-11-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0017_data_migrate_warning_stops"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fastlinkwarning",
            name="stops",
        ),
        migrations.RemoveField(
            model_name="fasttimingwarning",
            name="stops",
        ),
        migrations.RemoveField(
            model_name="firststopsetdownonlywarning",
            name="stops",
        ),
        migrations.RemoveField(
            model_name="laststoppickuponlywarning",
            name="stops",
        ),
        migrations.RemoveField(
            model_name="multiplestopswarning",
            name="stops",
        ),
        migrations.RemoveField(
            model_name="slowlinkwarning",
            name="stops",
        ),
        migrations.RemoveField(
            model_name="slowtimingwarning",
            name="stops",
        ),
    ]
