# Generated by Django 2.2.7 on 2019-12-02 22:40

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0018_auto_20191120_1732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclejourney",
            name="timing_pattern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_journeys",
                to="data_quality.TimingPattern",
            ),
        ),
        migrations.CreateModel(
            name="DataQualityReportSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_quality.DataQualityReport",
                    ),
                ),
            ],
        ),
    ]
