# Generated by Django 2.2.7 on 2019-11-28 10:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0018_auto_20191120_1732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclejourney",
            name="timing_pattern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_journeys",
                to="data_quality.TimingPattern",
            ),
        ),
        migrations.CreateModel(
            name="StopMissingNaptanWarning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_quality.DataQualityReport",
                    ),
                ),
                (
                    "stops",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_quality.StopPoint",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
