# Generated by Django 2.2.7 on 2019-12-02 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0019_auto_20191202_2240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataqualityreportsummary",
            name="report",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary",
                to="data_quality.DataQualityReport",
            ),
        ),
    ]
