# Generated by Django 2.2.7 on 2019-11-28 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0020_auto_20191128_1638"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePatternServiceLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                (
                    "service_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_pattern_service_links",
                        to="data_quality.ServiceLink",
                    ),
                ),
                (
                    "service_pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_pattern_service_links",
                        to="data_quality.ServicePattern",
                    ),
                ),
            ],
            options={
                "unique_together": {("service_pattern", "service_link", "position")},
            },
        ),
    ]
