# Generated by Django 2.2.7 on 2019-11-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0022_timingdropoffwarning"),
        ("data_quality", "0022_timingbackwardswarning"),
    ]

    operations = []
