# Generated by Django 2.2.7 on 2019-11-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0023_merge_20191129_1558"),
        ("data_quality", "0023_merge_20191129_1620"),
    ]

    operations = []
