# Generated by Django 2.2.7 on 2019-11-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0024_merge_20191129_1824"),
        ("data_quality", "0022_stopmissingnaptanwarning"),
    ]

    operations = []
