# Generated by Django 2.2.7 on 2019-12-02 10:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0026_timingmissingpointwarning"),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyDateRangeBackwardsWarning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_quality.DataQualityReport",
                    ),
                ),
                (
                    "vehicle_journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_quality.VehicleJourney",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
