# Generated by Django 2.2.7 on 2019-12-02 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0026_timingmissingpointwarning"),
    ]

    operations = [
        migrations.AddField(
            model_name="timingbackwardswarning",
            name="from_stop",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_stop",
                to="data_quality.TimingPatternStop",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timingbackwardswarning",
            name="to_stop",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_stop",
                to="data_quality.TimingPatternStop",
            ),
            preserve_default=False,
        ),
    ]
