# Generated by Django 2.2.7 on 2019-12-02 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0029_auto_20191202_1739"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journeyduplicatewarning",
            name="duplicate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicate",
                to="data_quality.VehicleJourney",
            ),
        ),
    ]
