# Generated by Django 2.2.7 on 2019-12-03 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0020_auto_20191202_2253"),
        ("data_quality", "0030_auto_20191202_1756"),
    ]

    operations = []
