# Generated by Django 2.2.7 on 2019-12-03 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0027_auto_20191202_1558"),
        ("data_quality", "0031_merge_20191203_0008"),
    ]

    operations = []
