# Generated by Django 2.2.8 on 2019-12-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0032_merge_20191203_1415"),
        ("data_quality", "0032_stopincorrecttypewarning"),
    ]

    operations = []
