# Generated by Django 2.2.8 on 2019-12-04 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0033_merge_20191203_1921"),
        ("data_quality", "0033_timingmultiplewarning"),
    ]

    operations = []
