# Generated by Django 2.2.7 on 2019-12-04 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0033_incorrectnocwarning"),
        ("data_quality", "0034_merge_20191204_1021"),
    ]

    operations = []
