# Generated by Django 2.2.8 on 2019-12-05 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0035_merge_20191204_1332"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicepattern",
            name="service_links",
        ),
    ]
