# Generated by Django 2.2.8 on 2019-12-04 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0035_merge_20191204_1332"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclejourney",
            name="dates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateField(), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
