# Generated by Django 2.2.8 on 2019-12-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0035_stopmissingnaptanwarning_service_patterns"),
    ]

    operations = [
        migrations.AddField(
            model_name="stopincorrecttypewarning",
            name="service_patterns",
            field=models.ManyToManyField(to="data_quality.ServicePattern"),
        ),
    ]
