# Generated by Django 2.2.8 on 2019-12-04 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0036_stopincorrecttypewarning_service_patterns"),
        ("data_quality", "0036_timingfirstwarning"),
        ("data_quality", "0036_vehiclejourney_dates"),
    ]

    operations = []
