# Generated by Django 2.2.8 on 2019-12-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0036_remove_servicepattern_service_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepattern",
            name="service_links",
            field=models.ManyToManyField(
                related_name="service_patterns",
                through="data_quality.ServicePatternServiceLink",
                to="data_quality.ServiceLink",
            ),
        ),
    ]
