# Generated by Django 2.2.8 on 2019-12-05 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0039_journeystopinappropriatewarning"),
        ("data_quality", "0039_journeyconflictwarning"),
    ]

    operations = []
