# Generated by Django 2.2.8 on 2019-12-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0039_journeywithoutheadsignwarning"),
        ("data_quality", "0040_merge_20191205_1737"),
    ]

    operations = []
