# Generated by Django 2.2.7 on 2019-12-06 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0041_merge_20191206_1144"),
        ("data_quality", "0041_auto_20191206_1213"),
    ]

    operations = []
