# Generated by Django 2.2.19 on 2021-03-25 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0048_ptiobservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptiobservation",
            name="revision",
            field=models.ForeignKey(
                help_text="The revision that observation occurred in.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pti_observations",
                to="organisation.DatasetRevision",
            ),
        ),
    ]
