# Generated by Django 2.2.19 on 2021-03-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0049_pti_related_name_added"),
        ("data_quality", "0049_pti_add_reference_field"),
    ]

    operations = []
