# Generated by Django 2.2.22 on 2021-05-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0052_remove_unused_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataqualityreport",
            name="score",
            field=models.FloatField(default=0.0, verbose_name="Data quality score"),
        ),
        migrations.AddConstraint(
            model_name="dataqualityreport",
            constraint=models.CheckConstraint(
                check=models.Q(("score__gte", 0.0), ("score__lte", 1.0)),
                name="dq_score_must_be_between_0_and_1",
            ),
        ),
    ]
