# Generated by Django 2.2.23 on 2021-06-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0053_report_score"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stoppoint",
            unique_together={("ito_id", "atco_code", "is_provisional")},
        ),
    ]
