# Generated by Django 2.2.24 on 2021-07-01 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0055_add_pti_results_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptivalidationresult",
            name="report",
            field=models.FileField(
                upload_to="",
                validators=[django.core.validators.FileExtensionValidator([".zip"])],
            ),
        ),
    ]
