# Generated by Django 3.1.13 on 2021-09-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0056_added_file_extension_validator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataqualityreportsummary",
            name="data",
            field=models.JSONField(),
        ),
    ]
