# Generated by Django 3.2.20 on 2023-10-02 15:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0058_auto_20230113_1621"),
        ("data_quality", "0057_auto_20210930_1524"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostSchemaViolation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="The name of the file the observation occurs in.",
                        max_length=256,
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        help_text="Details of the observation.", max_length=1024
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True,
                        verbose_name="DateTime observation was created.",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        help_text="The revision that observation occurred in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_schema_violations",
                        to="organisation.datasetrevision",
                    ),
                ),
            ],
        ),
    ]
