# Generated by Django 4.2.9 on 2024-04-12 16:48

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0059_alter_dataset_dataset_type"),
        ("transmodel", "0021_stopactivity_vehiclejourney_block_number"),
        ("data_quality", "0058_postschemaviolation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation", models.CharField(max_length=1024)),
                ("importance", models.CharField(max_length=64)),
                ("category", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="TaskResults",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=64)),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Contains more details about the error"
                    ),
                ),
                (
                    "checks",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dqs_taskresults_check",
                        to="data_quality.checks",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dqs_report",
                        to="organisation.datasetrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ErrorResults",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Contains more details about the error"
                    ),
                ),
                (
                    "service_pattern_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dqs_errorresult_service_pattern_stop",
                        to="transmodel.servicepatternstop",
                    ),
                ),
                (
                    "taskresults",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dqs_errorresult_taskresults",
                        to="data_quality.taskresults",
                    ),
                ),
                (
                    "vehicle_journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dqs_errorresult_vehicle_journey",
                        to="transmodel.vehiclejourney",
                    ),
                ),
            ],
        ),
    ]
