# Generated by Django 4.2.14 on 2025-02-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0058_postschemaviolation"),
    ]

    operations = [
        migrations.AddField(
            model_name="postschemaviolation",
            name="additional_details",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="postschemaviolation",
            name="details",
            field=models.CharField(
                choices=[
                    ("PII ERROR", "PII Error"),
                    ("SERVICE EXISTS", "Service Exists"),
                ],
                help_text="Details of the observation.",
                max_length=1024,
            ),
        ),
    ]
