# Generated by Django 4.2.14 on 2024-09-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_quality", "0058_postschemaviolation"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptivalidationresult",
            name="filenames",
            field=models.TextField(blank=True, null=True),
        ),
    ]
