# Generated by Django 4.1.13 on 2024-04-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0059_alter_dataset_dataset_type"),
        ("data_quality", "0059_checks_taskresults_report_observationresults"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="taskresults",
            name="dataquality_report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dqs_taskresults_report",
                to="data_quality.report",
            ),
        ),
        migrations.AddField(
            model_name="taskresults",
            name="transmodel_txcfileattributes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dqs_taskresults_txcfileattributes",
                to="organisation.txcfileattributes",
            ),
        ),
    ]
