# Generated by Django 4.1.13 on 2024-05-13 17:39

from django.db import migrations
from transit_odp.data_quality.constants import CHECKS_DATA


def insert_data(apps, schema_editor):
    Checks = apps.get_model("data_quality", "Checks")
    for entry in CHECKS_DATA:
        Checks.objects.create(**entry)


class Migration(migrations.Migration):
    dependencies = [
        ("data_quality", "0060_report_status_taskresults_dataquality_report_and_more"),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
