# Generated by Django 3.0.14 on 2021-09-02 10:29

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnownIssues",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "category",
                    models.CharField(
                        choices=[("consumer", "Consumer"), ("publisher", "Publisher")],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("fixed", "Fixed")],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsumerKnownIssues",
            fields=[],
            options={
                "verbose_name": "Consumer Known Issues",
                "verbose_name_plural": "Consumer Known Issues",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("changelog.knownissues",),
        ),
        migrations.CreateModel(
            name="PublisherKnownIssues",
            fields=[],
            options={
                "verbose_name": "Publisher Known Issues",
                "verbose_name_plural": "Publisher Known Issues",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("changelog.knownissues",),
        ),
    ]
