# Generated by Django 3.0.14 on 2021-09-02 10:54

from django.db import migrations


def add_coming_soon(apps, schema_editor):
    HighLevelRoadMap = apps.get_model("changelog", "HighLevelRoadMap")
    HighLevelRoadMap.objects.create(description="Coming soon")


class Migration(migrations.Migration):
    dependencies = [
        ("changelog", "0002_high_level_roadmap"),
    ]

    operations = [
        migrations.RunPython(add_coming_soon),
    ]
