name: Delete Stale Branches

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Delete stale branches
        run: |
          DEFAULT_BRANCH='dev'
          stale_branches=$(git branch --merged $DEFAULT_BRANCH --format '%(refname:short)' | grep -vE "^($DEFAULT_BRANCH|main|test)$")
          for branch in $stale_branches; do
            last_commit_date=$(git log -1 --format="%ci" $branch)
            days_ago=$(( ($(date +%s) - $(date -d "$last_commit_date" +%s)) / 86400 ))
            if [ $days_ago -gt 60 ]; then
              echo "Branch to delete is: $branch"
            fi
          done
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
