name: Delete Stale Branches

on:
  schedule:
    - cron: "0 0 * * *" # Everday at midnight

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v1.6.0
        with:
          dry-run: false # Check out the console output before setting this to false
          days-before-branch-stale: 60
          exempt-branches-regex: ^(main|dev|test)$
          exempt-protected-branches: true
          operations-per-run: 100