name: Delete Stale Branches

on:
  push:
    branches:
      - github_action
  schedule:
    - cron: "*/55 * * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Delete stale branches
        shell: bash
        run: |
          DAYS_THRESHOLD=60
          for branch in $(git branch | sed '/\*/d'); do
              echo "$branch"
              last_commit_timestamp=$(git log -1 --pretty=format:"%ct" "$branch")
              echo "$last_commit_timestamp"
              days_ago=$(( ( $(date +%s) - last_commit_timestamp ) / 86400 ))
              if [ "$days_ago" -gt "$DAYS_THRESHOLD" ]; then
                  # git branch -D "$branch"
                  echo "Deleted stale branch: $branch"
              fi
          done
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
