name: Delete Stale Branches

on:
  push:
    branches:
      - github_action
  schedule:
    - cron: "*/55 * * * *"

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v1.6.0
        with:
          dry-run: true # Check out the console output before setting this to false
