name: Delete Stale Branches

on:
  push:
    branches:
      - github_action
  schedule:
    - cron: "*/55 * * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Delete stale branches
        run: |
          DEFAULT_BRANCH='dev'
          DAYS_THRESHOLD=60
          stale_branches=$(git branch --merged $DEFAULT_BRANCH --format '%(refname:short)' | grep -vE "^($DEFAULT_BRANCH|main|test)$")
          for branch in $stale_branches; do
              last_commit_timestamp=$(git log -1 --pretty=format:"%ct" "$branch")
              days_ago=$(( ( $(date +%s) - last_commit_timestamp ) / 86400 ))
              if [ "$days_ago" -gt "$DAYS_THRESHOLD" ]; then
                  # git branch -D "$branch"
                  echo "Deleted stale branch: $branch"
              fi
          done
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
